### ISSUE TITLE
Idea: Dockerize

### ISSUE THREAD

**Issue by curator888** [redcanaryco/atomic-red-team#1039]
# Request

Dockerize to aid in quick simple deployment in a Docker environment.

**Comment by keithmccammon** [comment]
@curator888 Are you suggesting a Docker setup file for Atomic Red Team, or Invoke-Atomic?

**Comment by igodfrey92** [comment]
@curator888 I wrote a Dockerfile and entrypoint script for Invoke-Atomic that downloads atomic red team prior to running tests you might find useful. Definitely a work in progress so let me know what you think https://github.com/igodfrey92/invoke-atomicredteam/tree/invoke-container

**Comment by amashinchi-rc** [comment]
@curator888 apologies for the (very) delayed response/actioning on this issue!

Going to Close this one, as it does not seem to be relevant for Atomic Red Team itself as, 

1. this project is a library, not software; therefore there is nothing to "run" or deploy.
2. the execution frameworks have their own strategies for deployment. (such as @igodfrey92 's awesome example!)

Please reach out if you have any additional thoughts!
