### ISSUE TITLE
possible typo in T1033 command

### ISSUE THREAD

**Issue by emrahkaya** [redcanaryco/atomic-red-team#1040]
I think there's an extra quote in the command:
https://github.com/redcanaryco/atomic-red-team/blob/14905c7a1618fe52bc0973ac575949ab4f9c2d67/atomics/T1033/T1033.yaml#L31

The command should start with `qwinsta.exe`, instead of `qwinsta.exe"`.

**Comment by clr2of8** [comment]
fixed, thank you
