### ISSUE TITLE
T1089: missing Windows firewall (netsh) tests

### ISSUE THREAD

**Issue by cnotin** [redcanaryco/atomic-red-team#1044]
T1089 covers many techniques, including modification of system firewall which is now the T1562.004 sub-technique "Impair Defenses: Disable or Modify System Firewall"

Currently there is only one test which only covers Linux "Atomic Test #1 - Disable iptables firewall"

I suggest adding tests for Windows using netsh, either to completely disable the firewall:
```
netsh advfirewall set currentprofile state off
NetSh Advfirewall set allprofiles state off
````
Or to allow specific ports/programs:
```
netsh advfirewall firewall add rule name="<service’s name>" dir=in action=allow service="<service’s name>" enable=yes
netsh firewall addallowedprogram "c:\windows\system32\svchost.exe -k <service’s name>" "<service name>" enable
```

Enabling the already existing RDP rule is also very common for attackers:
```
netsh advfirewall firewall set rule group="remote desktop" new enable=Yes
netsh advfirewall firewall set rule group="file and printer sharing" new enable=Yes
```
Or:
```
netsh firewall set service type = remotedesktop mode = enable
netsh firewall set service type = fileandprint mode = enable
```

**Comment by clr2of8** [comment]
This is a great suggestion. I see you have submitted several PR's recently, are you up for added this as a PR, or would you like someone else to take this task?

**Comment by cnotin** [comment]
I can try something :)

**Comment by cnotin** [comment]
Here we go!
