### ISSUE TITLE
T1070: stopping the eventlog process makes following test fail

### ISSUE THREAD

**Issue by cnotin** [redcanaryco/atomic-red-team#1052]
# Report

## What did you do?
Run all tests for T1070:
```powershell
PS C:\Windows\system32> Invoke-AtomicTest T1070
PathToAtomicsFolder = C:\AtomicRedTeam\atomics

Executing test: T1070-1 Clear Logs
Done executing test: T1070-1 Clear Logs
Executing test: T1070-2 FSUtil
Done executing test: T1070-2 FSUtil
Executing test: T1070-6 Delete System Logs Using PowerShell
Done executing test: T1070-6 Delete System Logs Using PowerShell
Executing test: T1070-7 Delete System Logs Using Clear-EventLogId
Clear-EventLog : The operating system reported an error when writing the event entry to the event log. A Windows
error code is not available.
At line:1 char:4
+ & {Clear-EventLog -logname Application}
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ReadError: (:) [Clear-EventLog], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.ClearEventLogCommand

Done executing test: T1070-7 Delete System Logs Using Clear-EventLogId
```

## What did you expect to happen?

Test #7 succeeds

## What happened instead?

Test #7 fails
The error in test #7 is due to the fact that the previous test #6 just stopped the EventLog service. It restarts automatically but it waits 1 minute for this, so it isn't restarted yet when running test #7

I have a few ideas but nothing really satisfactory:
* put test that stops the service last, but issue will come back if we add a new test
* restart it in test #6 as the cleanup command does
* add a delay, but we don't want to impact running a single test

## Your Environment
N/A

**Comment by clr2of8** [comment]
I just submitted PR #1142  to resolve issue #1105 and remove the test you are talking about. I believe this also resolves this issue. I will close this out for now but we can re-open if it doesn't fully address the problem. thx

**Comment by cnotin** [comment]
That's one way to fix it :)
