### ISSUE TITLE
Add new elevation_required mode: SYSTEM

### ISSUE THREAD

**Issue by cnotin** [redcanaryco/atomic-red-team#1054]
# Report

## What did you do?

I tried running T1003-2 as admin:
```powershell
PS C:\> Invoke-AtomicTest T1003 -TestNumbers 2
PathToAtomicsFolder = C:\AtomicRedTeam\atomics

Executing test: T1003-2 Gsecdump
warning: 'execute self as a service' feature is not implemented
dump_wireless: error: not implemented
dump_lsa: error: failed to open registry key (access is denied)
dump_usedhashes: error: failed to resolve all required functions
dump_hashes: remote thread error: 0xc0000008
Done executing test: T1003-2 Gsecdump
```

## What did you expect to happen?

It should run because I'm admin

## What happened instead?

Actually it fails because the gsecdump `dump_lsa` module needs `NT AUTHORITY\SYSTEM`
It works better as SYSTEM:
```powershell
PS C:\Windows\system32> whoami
nt authority\system
PS C:\Windows\system32> Invoke-AtomicTest T1003 -TestNumbers 2
PathToAtomicsFolder = C:\AtomicRedTeam\atomics

Executing test: T1003-2 Gsecdump
dump_wireless: error: not implemented
DefaultPassword
DPAPI_SYSTEM
 01 00 00 00 27 AA CC 77 FF 8B 73 D4 7D A2 40 55  ....'..w..s.}.@U  __??????
[...]
L$_SQSA_S-1-5-21-2047410079-3110891331-4161008849-1001
 7B 00 22 00 76 00 65 00 72 00 73 00 69 00 6F 00  {.".v.e.r.s.i.o.  {"versio
[...]
NL$KM
 BE 49 34 6E 14 4C B1 6F 00 8C DA 8B AC E1 55 2B  .I4n.L.o......U+  ??????__
[...]
dump_usedhashes: error: failed to resolve all required functions
dump_hashes: remote thread error: 0xC0000008
Done executing test: T1003-2 Gsecdump
```
Other errors are probably due to the fact that it's an old tool running on a very recent Win10

I suggest adding a new setting similar to `elevation_required`, like `very_high_elevation_required`

## Your Environment
See above

**Comment by MHaggis** [comment]
We're going to close this for now and review again later as Windows 10 may effectively be ending this technique (outside of using system).

**Comment by cnotin** [comment]
I'm curious about:
> Windows 10 may effectively be ending this technique (outside of using system).

Can you please tell me more @MHaggis?
Either I didn't understand you, or I would be very surprised!

**Comment by MHaggis** [comment]
Apologies! 
Mostly meaning gsecdump is old and per your comment not completing execution well on Win10. The artifact traces may be useful in its current state. But, right now we will monitor this as a potential future item.

**Comment by cnotin** [comment]
Indeed some features of this old tool don't work on Win10 :)
I was wondering if other TTPs might need SYSTEM too, in addition to admin privileges (which was the root goal of this issue) but I can't find any for now!
