### ISSUE TITLE
T1574.006 missing T1574.006.c source code

### ISSUE THREAD

**Issue by Meow-ops** [redcanaryco/atomic-red-team#1067]
# Report

## What did you do?
tried implementing the T1574.006

## What did you expect to happen?
Having all the proposer information to execute the attack

## What happened instead?

Did not find T1574.006.c, the source code for the T1574.006.so library

## Your Environment

https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1574.006/T1574.006.md

**Comment by Tsora-Pop** [comment]
https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1574.006/src/Linux/T1574.006.c
Perhaps there another issue? T1574.006.c exists.

**Comment by Meow-ops** [comment]
Ho ok, it's just that there are no links in the md file towards the source code, I got confused. I don't know if it should be improved but I am closing the issue then.
