### ISSUE TITLE
T1197: The bitsadmin.exe /resume AtomicBITS is failing.

### ISSUE THREAD

**Issue by ironmanstittsville** [redcanaryco/atomic-red-team#1081]
# Report

## What did you do?
Using a Powershell terminal:
>Invoke-AtomicTest T1197 -TestNumbers 3

## What did you expect to happen?
I expected to see notepad.exe launched and a T1197 markdown file loaded. 

## What happened instead?
I just got an error from the final bitsadmin.exe command in that test case. The final command in that test case is:
>bitsadmin.exe /resume AtomicBITS

The failure that I get is:
>Unable to find job named "AtomicBITS".

NOTE: the list of commands in this test case are:
```
bitsadmin.exe /create #{bits_job_name}
bitsadmin.exe /addfile #{bits_job_name} #{remote_file} #{local_file}
bitsadmin.exe /setnotifycmdline #{bits_job_name} #{command_path} #{command_line}
bitsadmin.exe /complete AtomicBITS
bitsadmin.exe /resume #{bits_job_name}
```
The problem is that the /complete command causes the job to complete and now it no longer exists in the BITS list. The /resume could be run before the /complete to avoid this problem.

I have tried switching the order of those 2 bitsadmin commands but I get a different problem. The notepad launches as it should but there is no file loaded. I don't know why that is, I can see the file in the file system.

## Your Environment

* Which *specific* operating system are you running (e.g. Windows 7 SP1 32-bit)?
Win10 x64
* Did you run the test from an elevated or root prompt?
No, a user prompt.
* If relevant, which atomic test is this specific to?
T1197 BITS
* If relevant, which [execution harness](2) are you attempting to use?
I'm using the powershell invoker.

[1]: https://github.com/redcanaryco/atomic-red-team/tree/master/atomics "atomic tests"
[2]: https://github.com/redcanaryco/atomic-red-team/tree/master/execution-frameworks "execution frameworks"

**Comment by cnotin** [comment]
Can you please check https://github.com/redcanaryco/atomic-red-team/pull/1048 ?

**Comment by ironmanstittsville** [comment]
Whoops, #1048 is exactly the issue that I've found. The fix for that will address this.
