### ISSUE TITLE
Add '-accepteula' flag to all Sysinternals/PsTools

### ISSUE THREAD

**Issue by cnotin** [redcanaryco/atomic-red-team#1092]
# Report

## What did you do?

I used T1569.002

## What did you expect to happen?

If we want tests to run smoothly (and potentially automatically in the background) we should add the '-accepteula' flag to all Sysinternals/PsTools commands. This is done on some of them, but not all, for example:
https://github.com/redcanaryco/atomic-red-team/blob/75bf6ed382fa052b7028793f7806fff92545d02a/atomics/T1569.002/T1569.002.yaml#L60

I put it here as a reminder if someone wants to do it. Unfortunately I cannot do it thoroughly on the whole code base right now.

## What happened instead?

I had to accept PsExec's EULA

**Comment by cherokeejb** [comment]
Thanks for the tip Clément @cnotin .  I've identified the below 4 lines, including your example, where the sysinternals tools' -accepteula flag was not set, and am in the process of adding them:
1) psexec:
atomic-red-team/atomics/T1569.002/T1569.002.yaml
2) T1021 test 2
3) T1021 test 6
4) autoruns:
atomics/T1564.004/T1564.004.yaml

I did search for all 16 of the tools documented at [https://docs.microsoft.com/en-us/sysinternals/downloads/system-information]

I've also put in a request that these type of commands be highlighted in the spec.yaml instructional document.  I hadn't realized this is quite a common Windows flag, it was used also 4 times in the repos already. 

I also read that .."f the reg key above is set to 0 (EULA was declined once) then the /accepteula will not work, you have to set the key to 1 manually (or delete it altogether)." So to do it properly each test would  maybe need to also check that reg key (what do you think about that part @clr2of8 - it would essentially cause it to also trigger registry-related alerts.  See [https://stackoverflow.com/questions/5151034/psexec-gets-stuck-on-licence-prompt-when-running-non-interactively].

**Comment by cherokeejb** [comment]
https://github.com/redcanaryco/atomic-red-team/pull/1144
