### ISSUE TITLE
Suggestion: systematically add ATT&CK IDs in created artifacts

### ISSUE THREAD

**Issue by cnotin** [redcanaryco/atomic-red-team#1097]
When running several tests one after the other, or running a set of tests for the same ATT&CK technique, it's often hard to cross reference afterwards what we launched with what we see in EDR telemetry for example. Especially if we don't want to wait and see between each single test. That's why I think it would be helpful to integrate somewhere the Technique ID in the execution attempt. For example in the file or process name when the test create one. Some already do and it's very convenient.
I suggest generalizing it.

Just a suggestion here. That would take some work so collecting your thoughts before 🙂

**Comment by clr2of8** [comment]
That is a very helpful idea. As maintainers we could help by watching for this and suggesting it for new contributions.

**Comment by clr2of8** [comment]
Closing for now. Suggestion noted and passed on to maintainers. Several good examples to follow now in the code.
