### ISSUE TITLE
Invalid Syntax for Multiline field in T1003.001 yaml on line 111

### ISSUE THREAD

**Issue by bdenker** [redcanaryco/atomic-red-team#1122]
## What did you do?
Invoke-AtomicTest T1003.001 -TestName "Dump LSASS.exe Memory using direct system calls and API unhooking"

## What did you expect to happen?
Received error for syntax error for multiline field - invalid syntax on line 111.

## What happened instead?
Test would not validate

## Your Environment

* Windows 10
* Elevated prompt
* T1003.001
* Dump LSASS.exe Memory using direct system calls and API unhooking

[1]: https://github.com/redcanaryco/atomic-red-team/tree/master/atomics "atomic tests"
[2]: https://github.com/redcanaryco/atomic-red-team/tree/master/execution-frameworks "execution frameworks"

**Comment by clr2of8** [comment]
Also, as an experiment, can you put a pipe symbol at the end of line 111 as follows to see if this fixes it?

![image](https://user-images.githubusercontent.com/22311332/87575663-7727b200-c68d-11ea-90a6-bf3d9cfb0487.png)

**Comment by bdenker** [comment]
The pipe symbol is missing from the original syntax to denote a multi-line field. Adding in the | fixes it on my end.

**Comment by clr2of8** [comment]
OK, i'm on 4.1 so it must have gotten more strict on requiring the pipe. I'll upgrade and confirm, then fix any missing pipe symbols in the yaml files. Thanks for bringing this to our attention.

**Comment by clr2of8** [comment]
I upgraded powershell-yaml to 0.4.2 but it is not complaining about the missing pipe. Not sure why it did for you.

**Comment by bdenker** [comment]
Thank you for testing it. I'm not sure why either. For my use case for now I've added in the pipe and it works. Appreciate the assistance.

**Comment by clr2of8** [comment]
Corrected the few tests missing the pipe in PR #1124
