### ISSUE TITLE
Question: Best way to Trigger Ruby Actions in bin

### ISSUE THREAD

**Issue by nbyt3** [redcanaryco/atomic-red-team#1136]
We are creating some new Atomics and was wondering the best way to trigger the scripts in bin upon pushing to our forked atomic repo. We are wanting to trigger the 'generate-atomic-docs.rb' and the 'generate-guids.rb' either before or after pushing to our forked repo. Should these scripts be run before the push or as an action afterwards?

**Comment by clr2of8** [comment]
This repo using CircleCI to automatically run those scripts when PR's are merged. It's pretty slick but I don't know if that will be a workable solution for you. I suggest getting on the Atomic Red Team Slack workspace if you are not already and asking your question in the General channel there. It's a very active and helpful community there.

**Comment by clr2of8** [comment]
If you get onto the slack workspace, please connected with me @OrOneEqualsOne, I'd love to chat about the additions you are making in your fork. https://slack.atomicredteam.io/
