### ISSUE TITLE
Problem: T1014 - No prereq and test fails

### ISSUE THREAD

**Issue by Scoubi** [redcanaryco/atomic-red-team#1153]
## What did you do?

ℹ Please replace this with what you did.
I tested both using WinRM to a remote system and locally. Here is the trace
```
Invoke-AtomicTest T1014 -session $sess -getpre                                                        
GetPrereq's for: T1014-3 Windows Signed Driver Rootkit Test                                                                            
No Preqs Defined

Invoke-AtomicTest T1014 -session $sess
PathToAtomicsFolder = C:\AtomicRedTeam\atomics

Executing test: T1014-3 Windows Signed Driver Rootkit Test
'puppetstrings' is not recognized as an internal or external command,
operable program or batch file.
Done executing test: T1014-3 Windows Signed Driver Rootkit Test

Invoke-AtomicTest T1014
PathToAtomicsFolder = C:\AtomicRedTeam\atomics

Executing test: T1014-3 Windows Signed Driver Rootkit Test
'puppetstrings' is not recognized as an internal or external command,
operable program or batch file.
Done executing test: T1014-3 Windows Signed Driver Rootkit Test
```

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.
I expected the script to 
- Use the file `puppetstrings.exe` that is in the `bin` folder
- Download `driver.sys` when I issued the `-getpreq` and use the file during the test

## What happened instead?

ℹ Please replace this with of what happened instead.
The test failed because of dependencies

## Your Environment

* Which *specific* operating system are you running (e.g. Windows 7 SP1 32-bit)?
I tested on 
- Windows 10
- Windows 2012
- Windows 2016

* Did you run the test from an elevated or root prompt?
Test from an elevated Powershell on my Windows 10
Tested from WinRM on both Windows server

* If relevant, which atomic test is this specific to?
T1014 test 3

* If relevant, which [execution harness](2) are you attempting to use?
Invoke-AtomicTest

[1]: https://github.com/redcanaryco/atomic-red-team/tree/master/atomics "atomic tests"
[2]: https://github.com/redcanaryco/atomic-red-team/tree/master/execution-frameworks "execution frameworks"

**Comment by MHaggis** [comment]
I added puppetstrings.exe as a prereq. We're not entirely sure how we want to handle the capcom.sys driver for this test, by either adding it to Atomic or use an external dependency. I did update the description to reference http://www.fuzzysecurity.com/tutorials/28.html which does provide a repo with the driver and some other items related to using it. In the meantime, I'll close this and we can circle back once we figure out the best way to handle the driver.
