### ISSUE TITLE
Idea: feature request for ATT&CK mapping layers 

### ISSUE THREAD

**Issue by zinint** [redcanaryco/atomic-red-team#1175]
### Use-cases
Useful map for test developers.

### Proposal
These are the latest and up to date ATT&CK mapping layers for ART:
- [JSON files](https://github.com/redcanaryco/atomic-red-team/tree/master/atomics/Indexes/Attack-Navigator-Layers)
- navigator embedded layers:
	- [for Windows](https://mitre-attack.github.io/attack-navigator/enterprise/#layerURL=https%3A%2F%2Fraw%2Egithubusercontent%2Ecom%2Fredcanaryco%2Fatomic%2Dred%2Dteam%2Fmaster%2Fatomics%2FIndexes%2FAttack%2DNavigator%2DLayers%2Fart%2Dnavigator%2Dlayer%2Dwindows%2Ejson);
	- [for MacOS](https://mitre-attack.github.io/attack-navigator/enterprise/#layerURL=https%3A%2F%2Fraw%2Egithubusercontent%2Ecom%2Fredcanaryco%2Fatomic%2Dred%2Dteam%2Fmaster%2Fatomics%2FIndexes%2FAttack%2DNavigator%2DLayers%2Fart%2Dnavigator%2Dlayer%2Dmacos%2Ejson);
	- [for GNU\Linux](https://mitre-attack.github.io/attack-navigator/enterprise/#layerURL=https%3A%2F%2Fraw%2Egithubusercontent%2Ecom%2Fredcanaryco%2Fatomic%2Dred%2Dteam%2Fmaster%2Fatomics%2FIndexes%2FAttack%2DNavigator%2DLayers%2Fart%2Dnavigator%2Dlayer%2Dlinux%2Ejson).

But there are no layers/JSONs with Comments containing an ART test's `.yaml` link (path to a file in ART's repository covering each technique).

### References
By Comments I mean these ones embedded in each layer:
![image](https://user-images.githubusercontent.com/28983182/89457327-e1ec7a80-d76d-11ea-9c11-2bcc2ef0fcbd.png)
E.g. [Sigma navigator embedded layer](https://mitre-attack.github.io/attack-navigator/enterprise/#layerURL=https%3A%2F%2Fraw%2Egithubusercontent%2Ecom%2Fzinint%2FOSCD%5FSigma%2DART%5FLayers%2Fmaster%2Fsigma%2Dcoverage%2Ejson) with Comments.

#### I'd like to ask you to add this feature, I think that would be a cool feature to add (:

**Comment by d1vious** [comment]
@zinint would the url to the generated md file be better since it is pretty printed version of the yaml? I gave this an attempt here: https://github.com/redcanaryco/atomic-red-team/pull/1530
