### ISSUE TITLE
Problem: T1216 - manage-bde.wsf Signed Script Command Execution, explicit use of C:\Windows\System32\manage-bde.wsf

### ISSUE THREAD

**Issue by gregohmyeggo** [redcanaryco/atomic-red-team#1203]
## What did you do?

ℹ Please replace this with what you did.
set comspec=#{command_to_execute}
cscript manage-bde.wsf

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.
Executes the signed manage-bde.wsf script with options to execute an arbitrary command.. This should spawn calc.exe (as indicated when "set comspec=C:\Windows\System32\calc.exe"

## What happened instead?

ℹ Please replace this with of what happened instead.
Input Error: Can not find script file "C:\Users\<user>\manage-bde.wsf"

Testing from an user level command prompt should explicitly indicate the file path of manage-bde.wsf (C:\Windows\System32\manage-bde.wsf).

## Your Environment

Windows10, normal user command prompt.

**Comment by clr2of8** [comment]
Thank you for reporting this. We were able to get a fix merged for this via PR #1204
