### ISSUE TITLE
Idea: Add support for cloud-based ATT&CK techniques 

### ISSUE THREAD

**Issue by keithmccammon** [redcanaryco/atomic-red-team#1209]
### Use-cases
As an Atomic Red Team user in a modern enterprise, I need to be able to perform tests against my cloud-based infrastructure, so that I can assess coverage of [cloud-based ATT&CK techniques](https://attack.mitre.org/matrices/enterprise/cloud/).

### Proposal
Identify and implement schema changes that enable Atomic Red Team to support cloud techniques. 

### References
N/A

**Comment by katyapotapov** [comment]
Would love to work on this! Currently working with [@burningion](https://github.com/burningion) on a framework that will allow us to run tests on Kubernetes clusters. Let me know what we can do to move this forward!

**Comment by keithmccammon** [comment]
cc: @d1vious on the Splunk team, with whom we've been discussing this.

**Comment by amashinchi-rc** [comment]
This is [done](https://github.com/redcanaryco/atomic-red-team/milestone/5?closed=1)!

Examples: https://github.com/redcanaryco/atomic-red-team/pulls?q=is%3Aclosed+is%3Apr+label%3Acloud+
