### ISSUE TITLE
[OSCD Initiative] Develop atomic test for Sigma rules (Linux)

### ISSUE THREAD

**Issue by yugoslavskiy** [redcanaryco/atomic-red-team#1219]
### Additional Details

- Subject: [Sigma project](https://github.com/Neo23x0/sigma/)
- Authors: @Neo23x0, @thomaspatzke
- Type: Detection Rules

Please comment the issue if you are going to solve it so nobody will intersect with you.

| Task # | ATT&CK Technique name/link                                                     | Sigma Rules                                                                                       |
|:------:|--------------------------------------------------------------------------------|:-------------------------------------------------------------------------------------------------:|
| 1      | [T1562.006](https://attack.mitre.org/techniques/T1562/006): Indicator Blocking | <ul><li>[lnx_auditd_auditing_config_change](https://github.com/Neo23x0/sigma/blob/master/rules/linux/auditd/lnx_auditd_auditing_config_change.yml)</li><li>[lnx_auditd_logging_config_change](https://github.com/Neo23x0/sigma/blob/master/rules/linux/auditd/lnx_auditd_logging_config_change.yml)</li></ul> |

**Comment by aw350m33d** [comment]
I'll take this task

**Comment by MHaggis** [comment]
OSCD initiative looks to be complete https://github.com/redcanaryco/atomic-red-team/pull/1273
