### ISSUE TITLE
Idea: Improve Rootkit Testing

### ISSUE THREAD

**Issue by ghost** [redcanaryco/atomic-red-team#1222]
### Use-cases

The Linux Atomic Test [rootkit](https://github.com/redcanaryco/atomic-red-team/tree/8a82e9b66a5b4f4bc5b91089e9f24e0544f20ad7/atomics/T1014)  test is not very adequate to test.  

Simply loading a kernel module is insufficient to test against actual rootkit capabilities.

### Proposal
Use [Diamorphine](https://github.com/m0nad/Diamorphine), which many red teams and adversaries use to evade detection already.

### References

[Diamorphine](https://github.com/m0nad/Diamorphine)

Provides the following capabilities.

1. Diverse kernel version support and compilation.

2. Hidden modules, Hidden Process, Hidden Files.

[NSA/FBI Drovorub report](https://media.defense.gov/2020/Aug/13/2002476465/-1/-1/0/CSA_DROVORUB_RUSSIAN_GRU_MALWARE_AUG_2020.PDF)

**Comment by rc-GeorgeAllen** [comment]
see #2052 re a basic diamorphine test.
