### ISSUE TITLE
Idea: Decide how we want to handle ARTifacts

### ISSUE THREAD

**Issue by keithmccammon** [redcanaryco/atomic-red-team#1245]
### Use-cases
Determine how we, as a maintainer team, will adjudicate changes to the ARTifacts directory.

### Proposal
Our options may be something like:

1. Deprecate it
2. Freeze it (no more changes, leave existing as-is) -- this seems like technical debt
3. Document the standards applied to ARTifacts and enforce them

### References
* [Discussion in #maintainers](https://atomicredteam.slack.com/archives/GQCE6U23W/p1601958596026900)

**Comment by amashinchi-rc** [comment]
Closed as of PR #1408
