### ISSUE TITLE
Problem: It appears someone has committed a file named ".." into every directory.

### ISSUE THREAD

**Issue by secdev-01** [redcanaryco/atomic-red-team#1293]
## What did you do?

As I browse the repo I see ".." files in every path. I think a git exclusion would be helpful, though I am not sure.
## What did you expect to happen?
To not have spurious files in each folder.
## What happened instead?
I see ".." at the top of each page/code listing?

ℹ Please replace this with of what happened instead.

See attached screenshots.

![Screen Shot 2020-11-19 at 11 09 44 AM](https://user-images.githubusercontent.com/65909241/99707060-3257c180-2a59-11eb-9c63-0dd7c5c01ecf.png)

![Screen Shot 2020-11-19 at 11 09 56 AM](https://user-images.githubusercontent.com/65909241/99707066-34ba1b80-2a59-11eb-8bf0-062d33dd147c.png)

The problem seems to be pervasive?

**Comment by mgraeber-rc** [comment]
Hey could you point us to a commit where you suspect such a merge would have occurred? Otherwise, can you point us to how you might distinguish an actual `..` file from the feature of all GitHub repos where clicking `..` lets you navigate to the parent directory?

**Comment by secdev-01** [comment]
That makes sense, my mistake.  :)
