### ISSUE TITLE
Problem:  T1135 text is missing a backslash in  available shared drives using the net view \remotesystem

### ISSUE THREAD

**Issue by dave484** [redcanaryco/atomic-red-team#1340]
It's just a typo in  "available shared drives using the net view \remotesystem"

A backslash is missing.

**Comment by clr2of8** [comment]
Are you referring to the description here from Mitre ATT&CK? 
![image](https://user-images.githubusercontent.com/22311332/102824239-ab6c7080-4399-11eb-8944-e6385dd13f4d.png)

**Comment by dave484** [comment]
Yes, thank you.  That needs to be:  net view \\remotesystem

    On Monday, December 21, 2020, 04:37:47 PM EST, Carrie Roberts <notifications@github.com> wrote:  
 
 


Are you referring to the description here from Mitre ATT&CK?

**Comment by clr2of8** [comment]
Gotcha, that description comes from the Mitre ATT&CK website so an issue would need to be posted over "there" although I don't know exactly where "there" is. If you have trouble finding how to submit the issue to Mitre to have it fixed on their end ping me again and I'll ask around. Thanks for noticing.

**Comment by dave484** [comment]
Thank you, Carrie.

Dear attack@mitre.org,

There is an error on page https://attack.mitre.org/techniques/T1135/ 

The text is missing a backslash.  "remote system for available shared drives using the net view \remotesystem"

Should read  net view \\remotesystem

Thank you.

Dave




On Monday, December 21, 2020, 04:52:27 PM EST, Carrie Roberts <notifications@github.com> wrote: 







Gotcha, that description comes from the Mitre ATT&CK website so an issue would need to be posted over "there" although I don't know exactly where "there" is. If you have trouble finding how to submit the issue to Mitre to have it fixed on their end ping me again and I'll ask around. Thanks for noticing.
