### ISSUE TITLE
Problem: Invoke-WebRequest : Not Found

### ISSUE THREAD

**Issue by Healifiknow** [redcanaryco/atomic-red-team#1342]
## What did you do?

ℹ Please replace this with what you did.
Run 'Invoke-AtomicTest T1003.001 -TestNumbers 6 -GetPrereqs'

## What did you expect to happen?
The -CheckPrereqs Command ran fine issues appeared while trying to get prereqs.

ℹ Please replace this with what you expected to happen.
Download mimikatz from github.

## What happened instead
![image](https://user-images.githubusercontent.com/76654714/103173427-873ce380-4820-11eb-811d-56cfbecd9a13.png)

ℹ Please replace this with of what happened instead.
e.g. 💥

## Your Environment

* Windows 10 64-bit
* Did you run the test from an elevated or root prompt?
Ran in administrator command prompt 
* If relevant, which atomic test is this specific to?
* T1003.001 TestNumbers 6

**Comment by MHaggis** [comment]
Hi!
Test 6 was just updated yesterday https://github.com/redcanaryco/atomic-red-team/pull/1373

Let us know if you run into any issues. I'll keep this open for a few days.

https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1003.001/T1003.001.md#atomic-test-6---offline-credential-theft-with-mimikatz

**Comment by clr2of8** [comment]
closing as appears to be addressed
