### ISSUE TITLE
Problem: Running -GetPrereqs states already installed after errors displayed

### ISSUE THREAD

**Issue by Healifiknow** [redcanaryco/atomic-red-team#1343]
When running the -GetPrereqs command I get errors followed by the "Prereq already met:" message. I will be going through each command line by line as a part of my training, please advise if there are "must have" prereqs that are assumed to be installed prior to running. I was thinking the "-CheckPrereqs" and "-GetPrereqs" commands would cover these bases.

ℹ Please replace this with what you did.
Run 'Invoke-AtomicTest T1003.001 -TestNumbers 7 -GetPrereqs'

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.
Download "Python3", "pip3", "pypykatz"

## What happened instead?
![image](https://user-images.githubusercontent.com/76654714/103173767-d2f08c80-4822-11eb-9628-3a996ab5e87d.png)

ℹ Please replace this with of what happened instead.
e.g. 💥

## Your Environment

* Which *specific* operating system are you running (e.g. Windows 7 SP1 32-bit)?
Windows 10 64-bit

* Did you run the test from an elevated or root prompt?
Ran in Admin Command Prompt

**Comment by vbastomp** [comment]
Thanks for the info. It looks like there is a problem with the implementation of those prereqs. I've asked the author of that test to take a look.

**Comment by clr2of8** [comment]
Thanks for the info. It looks like there is a problem with the implementation of those prereqs. I've asked the author of that test to take a look. @morgansec

**Comment by clr2of8** [comment]
This was addressed today via PR #1388 , please open another issue if you find any problem. Thank you for reporting and thank you @morgansec for testing and submitting PR fix.
