### ISSUE TITLE
Problem:  T1014 failing puppetstrings failed - error: 00000003

### ISSUE THREAD

**Issue by Healifiknow** [redcanaryco/atomic-red-team#1344]
## What did you do?

ℹ Ran "Invoke-AtomicTest T1014 -TestNumbers 3"

## What did you expect to happen?

ℹ Atomic test to executes amd 'puppetstrings.exe' launches

## What happened instead?

ℹ
![image](https://user-images.githubusercontent.com/76654714/103180626-ffc19580-485c-11eb-9d3c-f4aa4f74257f.png)

## Your Environment

* Which *specific* operating system are you running (e.g. Windows 7 SP1 32-bit)?
Windows 10 64-bit
* Did you run the test from an elevated or root prompt?
Ran cmd as admin
* If relevant, which atomic test is this specific to?
T1014-3

**Comment by clr2of8** [comment]
Thanks for the report. Pull request merged to remove broken test.
