### ISSUE TITLE
Problem:  T1560.002 Archive Collected Data: Archive via Library wrong test.

### ISSUE THREAD

**Issue by akat12** [redcanaryco/atomic-red-team#1369]
## What did you do?

Tacttic: Exfiltration
Technique:  Archive Collected Data: Archive via Library https://attack.mitre.org/techniques/T1560/002/
 Compress and encrypt all collected data

echo "Testing: Zip up the Recon"
zip --password "Hope You Have Eyes on This!!" /tmp/.staging_art/loot.zip /tmp/.staging_art/* > /dev/null 2>&1

https://github.com/redcanaryco/atomic-red-team/blob/master/ARTifacts/Chain_Reactions/chain_reaction_Ranger.sh

## What did you expect to happen?

This test is incorrect for this particular tid and rather falls in the category T1560.001. This is because utilities require spawning a subshell, or a similar execution mechanism.
The proper test for this tid would be a loadlibrary event that loads an archival library. 

[1]: https://github.com/redcanaryco/atomic-red-team/tree/master/atomics "atomic tests"
[2]: https://github.com/redcanaryco/atomic-red-team/tree/master/execution-frameworks "execution frameworks"

**Comment by clr2of8** [comment]
ARTifacts have been removed from this repository.
