### ISSUE TITLE
T1550.003 - No bin folder

### ISSUE THREAD

**Issue by karenitas90** [redcanaryco/atomic-red-team#1370]
There isn't the bin folder for T1550.003, I want to test the mimikatz.exe file

**Comment by clr2of8** [comment]
Hi there karenitas90, you will find that some payload files are not included by default in the atomics folder. Instead, you can use the Prerequisite commands provided to download these files. For example, for T1550.003, the following commands are provided for checking if you have the needed files and also for getting them if you don't have them.
![image](https://user-images.githubusercontent.com/22311332/104762793-2c612280-5722-11eb-9f9f-b963e93c5576.png)
If you are using the PowerShell Execution Framework, you can simply use the following command before running the test which will create the bin folder and put mimikatz.exe in it.
`Invoke-AtomicTest T1550.003 -GetPrereqs`
