### ISSUE TITLE
Problem: 

### ISSUE THREAD

**Issue by sepehrafla** [redcanaryco/atomic-red-team#1372]
## What did you do?

Ran All the tests by Invoke-AtomicTest All -Confirtm:$false -ExecutionLogPath 'C:\Jan18.csv'

## What did you expect to happen?

run all the tests without issue

## What happened instead?

T1055.004 cause the system to restart I have ran this on DetectionLab VMs

**Comment by clr2of8** [comment]
I tested this today on Windows 10 and it didn't cause a restart. I'm closing this issue for now but if you find it is still happening feel free to reopen the issue and post the details. Thx
