### ISSUE TITLE
404 in tests 

### ISSUE THREAD

**Issue by JohnLaTwC** [redcanaryco/atomic-red-team#1385]
There are a couple of 404 links in this test. Perhaps this .sct file moved in the repo.

https://github.com/redcanaryco/atomic-red-team/blob/e529ce5732cae362991a5cba6cb18607d30e7863/ARTifacts/Labs/Webinar11062017-Labs.bat#L5

and here:
https://github.com/redcanaryco/atomic-red-team/blob/e529ce5732cae362991a5cba6cb18607d30e7863/ARTifacts/Labs/Webinar11062017-Labs.bat#L21

**Comment by clr2of8** [comment]
Archiving this issue now that ARTifacts themselves have been archived.
