### ISSUE TITLE
Problem: mavinject test in T1055 should be in T1055.001

### ISSUE THREAD

**Issue by mgraeber-rc** [redcanaryco/atomic-red-team#1404]
## What did you do?

There is a `mavinject.exe` injection test currently in T1055 that belongs in [T1055.001 - Process Injection: Dynamic-link Library Injection](https://attack.mitre.org/techniques/T1055/001/)

## What did you expect to happen?

I will move it out of T1055, do some cleanup of the `src` directory, and balance will be restored in the universe.

## What happened instead?

Balance was not restored in the universe but a technique was moved to a more appropriate location.

## Your Environment

Will validate in my Win10 VM

**Comment by clr2of8** [comment]
Thanks for correcting this one Matt
