### ISSUE TITLE
erorrs with wildcards related to yaml-cs branch

### ISSUE THREAD

**Issue by carnal0wnage** [redcanaryco/atomic-red-team#141]
atomic-red-team/atomics/T1002/T1002.yaml

while scanning an alias
  in "<unicode string>", line 34, column 16:
          default: *.docx
                   ^
expected alphabetic or numeric character, but found '.'
  in "<unicode string>", line 34, column 17:
          default: *.docx
                    ^

I bit of googling suggests if you want to have * at the beginning you will need to put it quotes

**Comment by brianebeyer** [comment]
Fixed in #155 and the validator will now correctly flag these issues
