### ISSUE TITLE
extra powershell.exe in command string T1002.yaml

### ISSUE THREAD

**Issue by carnal0wnage** [redcanaryco/atomic-red-team#142]
https://github.com/redcanaryco/atomic-red-team/blob/yaml-cs/atomics/T1002/T1002.yaml

If i'm reading the the various yaml's correctly you are setting the ```executor: powershell```
 and then NOT specifying the executor in the command. looks like you just have a rogue powershell.exe in this one

**Comment by brianebeyer** [comment]
Fixed in #155
