### ISSUE TITLE
Problem: Process Hooking T1056.004 Internet Explorer First Run Wizard and Automation

### ISSUE THREAD

**Issue by ghost** [redcanaryco/atomic-red-team#1425]
## What did you do?

Invoke-AtomicTest T1056.004 can result in an error on automated systems, where Internet Explorer has not run first.  

## What did you expect to happen?

Test to execute, without IE Errors / Exceptions

## What happened instead?

The following error occurs on IE first attempt in PowerShell. 
```
curl : The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's
first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again.
At line:2 char:1
+ curl https://www.example.com}
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotImplemented: (:) [Invoke-WebRequest], NotSupportedException
    + FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

```

## Your Environment

Detection Lab, Windows 10

## Proposed Workaround 

Internet Explorer First Run wizard can be disabled in the registry:

example:
$keyPath = 'Registry::HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Internet Explorer\Main'
if (!(Test-Path $keyPath)) { New-Item $keyPath -Force | Out-Null }
Set-ItemProperty -Path $keyPath -Name "DisableFirstRunCustomize" -Value 1

**Comment by clr2of8** [comment]
Thanks for the report. Pull request merged.
