### ISSUE TITLE
handling multi line commands in yaml files

### ISSUE THREAD

**Issue by carnal0wnage** [redcanaryco/atomic-red-team#143]
per request moving this over from twitter

ref:
https://twitter.com/carnal0wnage/status/994594132747317248

CG
are you guys planning to support multiple commands in in a single command item?  T1105.yaml has multiple commands. perhaps they could each be an element in a list (like you are doing supported_platforms). right now you'd/I have to account for # and blank lines

BB
Take a look at https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/t1089/t1089.yaml …  - isn’t completely in line with new spec yet but you’ll see the command is multiline.

Our thought was “write your commands like you’d write them in a bat/powershell/sh script and executors can invoke them as if a single script”

CG
hmmm how do you anticipate the executor invoking those? taking the blob and writing to a file and exec'ing? how would i exec all that if i only had ssh?

BB
For ssh, I think a heredoc works. Imagine the ssh+bash executor doing 

ssh user@host bash <<'EOF'
 << the contents of the executor.command >>
EOF

**Comment by carnal0wnage** [comment]
cc @brianebeyer  @caseysmithrc

**Comment by carnal0wnage** [comment]
@brianebeyer 

WINDOWS 

ref: Reading how you invoke winrm plus that plugin code... I *think* it might just work as you have it since Vagrant was designed to support ruby multiline commands in their provisioners

you might need to show me where you see that. I'm looking at: 

https://github.com/criteo/vagrant-winrm/blob/master/lib/vagrant-winrm/commands/winrm.rb

I'm not really seeing where it will accept multi line stuff. The example on the readme supports passing multiple -c commands but we'd still have to parse them out from the multiline blob of stuff.

**Comment by caseysmithrc** [comment]
Ok, so a good edge case came up. 
https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/t1130/t1130.md
This being an example of the benefit of just passing in the command block as a full script, rather than break out one liners

**Comment by carnal0wnage** [comment]
yeah. i'll propose here what i mentioned on the call and do a command: which is a list and something line command_block: | for multiline stuff that cant or shoudnt be broken up. 

thoughts?

**Comment by carnal0wnage** [comment]
thanks for the reply @brianebeyer  

couple of (my) concerns
1. linux/macos -> ```vagrant-ssh  <<'EOF' << the contents of the executor.command >> EOF```

while this might work, is pretty ugly,  I'll try to test this today with putting some comments, blank lines and stuff in that executor.command section and see how it goes.

2. windows -> i dont think its going to work with winrm, but like i mentioned in the call, i'd LOVE to be wrong here.  I linked above to what i think is the relevant code in the gem. please take a look and tell me what you think.

3. this may be irrelevant if 2 end up not being an issue, but  multiline support just puts \n for each line.  So the route i think most people (and myself) are going to go is split on the \n and either append it to a big string of ```powershell.exe line_one ; line_two, etc``` [dont know if the " ; " will even work that way and will that also work when cmd.exe is the command_executor ] or ```powershell.exe line_one``` then ```powershell.exe line_two```  
 - this is totally doable my question for you then is how will automation know NOT to do this in the example of https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/t1130/t1130.md 

I think the majority of the atomic tests will run thing sequentially, the above is my reasoning for suggesting a separate command_block option when the whole block of stuff should be executed differently.

thoughts?

**Comment by carnal0wnage** [comment]
working on this now

**Comment by caseysmithrc** [comment]
It has been decided.  Multiline wins. Closing
