### ISSUE TITLE
Problem: T1135-5 does not verify domain-joined computer

### ISSUE THREAD

**Issue by mboman** [redcanaryco/atomic-red-team#1441]
## What did you do?

PS C:\Users\WDAGUtilityAccount> `Invoke-AtomicTest T1135 -CheckPrereqs -TestNumbers 5`
```
PathToAtomicsFolder = C:\AtomicRedTeam\atomics

CheckPrereq's for: T1135-5 Share Discovery with PowerView
Prerequisites met: T1135-5 Share Discovery with PowerView                                    

```
PS C:\Users\WDAGUtilityAccount> `Invoke-AtomicTest T1135 -TestNumbers 5`
```
PathToAtomicsFolder = C:\AtomicRedTeam\atomics

Executing test: T1135-5 Share Discovery with PowerView
Done executing test: T1135-5 Share Discovery with PowerView
VERBOSE: [Find-DomainShare] Querying computers in the domain
VERBOSE: get-domain
VERBOSE: [Get-Domain] Error retrieving the current domain: Exception calling "GetCurrentDomain" with "0" argument(s):
"Current security context is not associated with an Active Directory domain or forest."
VERBOSE: [Get-DomainSearcher] search base: LDAP://
VERBOSE: [Get-DomainComputer] Get-DomainComputer filter string: (&(samAccountType=805306369))
VERBOSE: [Find-DomainShare] TargetComputers length: 0
Exception calling "FindAll" with "0" argument(s): "Unknown error (0x80005000)"
At line:6331 char:20
+             else { $Results = $CompSearcher.FindAll() }
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : COMException

[Find-DomainShare] No hosts found to enumerate
At line:18292 char:13
+             throw '[Find-DomainShare] No hosts found to enumerate'
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: ([Find-DomainSha...nd to enumerate:String) [], RuntimeException
    + FullyQualifiedErrorId : [Find-DomainShare] No hosts found to enumerate

```
## What did you expect to happen?

`-CheckPrereqs` to notice that it is not a domain-joined computer when doing the pre-flight check.

## What happened instead?

Test failed because computer not joined to a domain

## Your Environment

* Which *specific* operating system are you running (e.g. Windows 7 SP1 32-bit)?
    + Windows 10 2004 (OS Build 19041.928) [in a Windows Sandbox]
* Did you run the test from an elevated or root prompt?
    + Elevated Powershell prompt
* If relevant, which atomic test is this specific to?
    + T1135
* If relevant, which [execution harness](2) are you attempting to use?
    + Invoke-AtomicTest

[1]: https://github.com/redcanaryco/atomic-red-team/tree/master/atomics "atomic tests"
[2]: https://github.com/redcanaryco/atomic-red-team/tree/master/execution-frameworks "execution frameworks"

**Comment by MHaggis** [comment]
Added pre-req check and confirmed operational! Thank you!
