### ISSUE TITLE
Incorrect URL utilized in .inf file for T1218

### ISSUE THREAD

**Issue by gregohmyeggo** [redcanaryco/atomic-red-team#1449]
The embedded URL in infdefaultinstall.inf for test T1218 does not exist. The URL utilized for RegSvr32.sct will work in it's place. 

File: https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1218/src/Infdefaultinstall.inf
Current URL: https://raw.githubusercontent.com/redcanaryco/atomic-red-team/master/atomics/T1085/src/T1085.sct

Worked: https://raw.githubusercontent.com/redcanaryco/atomic-red-team/master/atomics/T1218.010/src/RegSvr32.sct

Additionally, the test case only executed when the .inf file was located in C:\Windows\System32.

**Comment by MHaggis** [comment]
Fixed! Thank you!
