### ISSUE TITLE
Problem: T1046 incorrect folder path

### ISSUE THREAD

**Issue by BoBoSiKi008** [redcanaryco/atomic-red-team#1458]
Issue

ℹ The issue comes from Update T1046.yaml #1436
The test #4 cannot be executed due to [Errno 2] No such file or directory.

![image](https://user-images.githubusercontent.com/58464478/117260203-69902280-ae81-11eb-9c83-c5331fd1b99d.png)

Request

ℹ Please change the folder name from scr to src.

**Comment by clr2of8** [comment]
fixed in PR #1460 thank you!
