### ISSUE TITLE
bitsadmin issue. /addfile parameters are incorrect. Fix included.

### ISSUE THREAD

**Issue by gregohmyeggo** [redcanaryco/atomic-red-team#1459]
## What did you do?

bitsadmin.exe /create AtomicBITS
bitsadmin.exe /addfile AtomicBITS https://raw.githubusercontent.com/redcanaryco/atomic-red-team/master/atomics/T1197/T1197.md %temp%\bitsadmin3_flag.ps1
bitsadmin.exe /setnotifycmdline AtomicBITS C:\Windows\system32\notepad.exe ""
bitsadmin.exe /resume AtomicBITS
timeout 5
bitsadmin.exe /complete AtomicBITS

## What did you expect to happen?

Added https://raw.githubusercontent.com/redcanaryco/atomic-red-team/master/atomics/T1197/T1197.md -> C:\Users\%\AppData\Local\Temp\bitsadmin3_flag.ps1 to job.

## What happened instead?

Unable to add file to job - 0x80070057
The parameter is incorrect.

## Your Environment

Standard Windows 10 Enterprise. Fresh build. No modifications.

FIX:
The "local_file" parameter should be **$env:TEMP\bitsadmin3_flag.ps1** and not **%temp%\bitsadmin3_flag.ps1**.

**Comment by gregohmyeggo** [comment]
Also, the same test case should include 'NULL' instead of the double quotes "" for the /setnotifycmdline.

When using double quotes "", an error is returned: Invalid number of arguments.

**Comment by MHaggis** [comment]
OKay, I think I got it fixed -
![image](https://user-images.githubusercontent.com/5632822/123336209-c8c5f700-d502-11eb-8eda-dcadb11424c1.png)

**Comment by clr2of8** [comment]
Closing as I believe this was addressed by PR #1535
