### ISSUE TITLE
Problem: Error while executing T1505.003 atomic with fix. 

### ISSUE THREAD

**Issue by Davdillion** [redcanaryco/atomic-red-team#1479]
Attempted to run https://github.com/redcanaryco/atomic-red-team/blob/8d0a5c454cf5bf5114685da572ee54d74b6c237f/atomics/T1505.003/

## What did you expect to happen?
 The atomic test executes and simulated web shell file are copied from "PathToAtomicsFolder\T1505.003\src\" to the default folder "C:\inetpub\wwwroot"

## What happened instead?
Error returned "Folder not found"

## Your Environment
Windows 10 x64
Ran elevated
T1505.003/T1505.003

## Fix
In T1505.003.yaml if the "\" is removed from the default path on line 20 "default: PathToAtomicsFolder\T1505.003\src\" the script runs successfully and copies the files from that folder to "C:\inetpub\wwwroot"

**Comment by clr2of8** [comment]
There are no longer quotes on line 20 and the test is working so I will close this out. Thx
