### ISSUE TITLE
Idea: Proposal for Atomic Red Team Spec changes to accommodate ATT&CK v9 (Cloud & Containers)

### ISSUE THREAD

**Issue by amashinchi-rc** [redcanaryco/atomic-red-team#1491]
### Use-cases

In order to support the MITRE ATT&CK changes made in v9 (Cloud Atomics, Containers, etc.)  the spec for Atomic Red Team needs to be expanded/modified to support new Platforms and Executors. With the key goals being:

1. Stay consistent with the terms and standards set by ATT&CK.
2. Provide mechanisms for users & automation to quickly find (and execute) relevant atomics; i.e. "how do I sort by only the atomics which work on AWS?"
3. Extend the use of `executors` to better accommodate cloud & container run-times.

#### A) Align `supported` platforms to support the ATT&CK defined platforms

This would require us to add the following to the `valid_supported_platforms` in Atomic Red Team:

- `office-365`
- `azure-ad`
- `google-workspace`
- `saas`
- `iaas`
- `containers`

#### B) Provide support for "platform tags" in Atomic Red Team

This allows the ability to use (Docker-like) tagging to specify a specific cloud provider, container technology, operating system, etc. However, the supported "sub-platforms" should not be arbitrary (created ad-hoc) and must be added to `valid_supported_platforms` in Atomic Red Team with agreement from Maintainers team.

Initial proposed "tags":

- `iaas:gcp`
- `iaas:azure`
- `iaas:aws`

Noting possibilities of later on adding items such as:

- `linux:ubuntu`
- `macos:mojave`
- etc.

#### C) Expanded support for "executors" in Atomic Red Team

This accommodates the use of third-party runtimes, specially in the context of Cloud and Containers. Example "executor names":

- `aws-cli`
- `gcp-cli`
- `azure-cli`

#### EXAMPLE YAML FILES

The attached takes two recent Cloud PR's and adjusts them to meet the above proposal standards.

[example_yaml_files.zip](https://github.com/redcanaryco/atomic-red-team/files/6586553/example_yaml_files.zip)

### References

- [Supported Platforms in Atomic Red Team](https://github.com/redcanaryco/atomic-red-team/blob/e37f8c617836589b418043cf249a8ce2ca6d114d/atomic_red_team/atomic_red_team.rb#L111)
-  [MITRE ATT&CK Updates - April 2021](https://attack.mitre.org/resources/updates/)
- [Proposed AWS Atomic](https://github.com/redcanaryco/atomic-red-team/pull/1457)
- [Proposed Azure AD Atomic](https://github.com/redcanaryco/atomic-red-team/pull/1454)

**Comment by d1vious** [comment]
This looks great! :tada: awesome work.
