### ISSUE TITLE
Website: Typo on Wiki

### ISSUE THREAD

**Issue by davehull-rc** [redcanaryco/atomic-red-team#1512]
### Why the change? 

My inner high school English teacher is perturbed.

### A summary of the change
The headline, "Things to Consider before Execute an Atomic Test" on this page, https://github.com/redcanaryco/atomic-red-team/wiki/Executing-Atomic-Tests should probably be "Things to Consider Before Executing an Atomic Test".

### References
No reference for the change from "Execute" to "Executing"
"before" to "Before" -> http://srjcstaff.santarosa.edu/~kthornle/30/CapitalizationMLAStyle.pdf

**Comment by d1vious** [comment]
hey I fixed it up, good point and awesome references thank you for the feedback :metal:
