### ISSUE TITLE
Problem: unescaped blackslash in T1546.008.md

### ISSUE THREAD

**Issue by hexnov** [redcanaryco/atomic-red-team#1539]
## What did you do?

Reading the _"Description from ATT&CK"_-section in the Markdown file for T1546.008 Accessibility Features.

## What did you expect to happen?

In the second paragraph it should say:
```
[...] the binary must reside in <code>%systemdir%\\</code>, and it must be protected [...]
```
With two backslashes after `%systemdir%`.

## What happened instead?

The backslash escapes the `<`, which results in the whole paragraph being a code block.

![Screenshot](https://user-images.githubusercontent.com/37831676/123921097-f25da300-d986-11eb-959c-f9d1cdbb3111.png)

## Your Environment

The MD previews in GitHub and VS Code.

**Comment by JoustingZebra** [comment]
Created pull request #1639 for fix.
