### ISSUE TITLE
Problem: T1136.002 "Create a new Domain Account using PowerShell" Cleanup command not working

### ISSUE THREAD

**Issue by Roinard** [redcanaryco/atomic-red-team#1543]
I executed the following test : T1136.002 "Create a new Domain Account using PowerShell"

I found out that the cleanup doesn't work correctly. The new Admin Domain Account is not removed properly.

When I execute the cleanup command : 
`net user "#{username}" >nul 2>&1 /del /domain`
I get : 
![image](https://user-images.githubusercontent.com/45967851/124480734-deaba580-dda7-11eb-963e-b694cc852945.png)
(Sorry for the image, I can't copy/paste)

In my opinion the problem come from the fact that the executor name is powershell, it seems to not like ">null". (The cleanup command work perfectly on cmd.exe).

I ran my test on Windows 10 64bits. 
Powershell version 5.1.19041.610

**Comment by clr2of8** [comment]
Could you test with this command and see if it works, if so, I can update the repo:
`net user "#{username}"  /del /domain >nul 2>&1`

**Comment by clr2of8** [comment]
oh sorry, you are referring to test 3, the PowerShell one ...

**Comment by clr2of8** [comment]
how about throw a `cmd /c ` in front?

**Comment by clr2of8** [comment]
fixed in PR #1548 . Thanks!
