### ISSUE TITLE
Idea: Run a single test e.g. T1059.001-1

### ISSUE THREAD

**Issue by jamesdeluk** [redcanaryco/atomic-red-team#1547]
### Use-cases

`T1059.001` has 18 different tests, and you can only run all of them at once. This makes it hard to monitor logs etc for results from an individual test.

Of course this applies to all, not just `T1059.001`.

### Proposal

Be able to run a single test, e.g. `Invoke-AtomicTest T1059.001-1`

**Comment by clr2of8** [comment]
Great Idea! and good news ... we've got you covered  ... Check out the options [here](https://github.com/redcanaryco/invoke-atomicredteam/wiki/Execute-Atomic-Tests-(Local)) for specifying a single test by name or number. In short, you can do this:
`Invoke-AtomicTest T1059.001 -TestNumber 1`

**Comment by jamesdeluk** [comment]
I feel stupid for missing that 🤦 Thanks!

**Comment by clr2of8** [comment]
Ha ha, no worries. It happens to me all the time :)
