### ISSUE TITLE
Idea: T1105 - Ingress tool transfer. Using cscript and wscript, call a script to download malicious code.

### ISSUE THREAD

**Issue by cccs-richardh** [redcanaryco/atomic-red-team#1596]
### Use case:
  Attacker has low privilege terminal access on the system and can run cscript and wscript. They plan to use those tools to download malicious files to the system. They could directly use cscript and wscript to launch a cmd shell and execute commands OR they could call another script in the hopes of avoiding detection/response (if the detection and response is designed to respond to cmd/pshell downloading files).

  In this specific case, I'd like a test that will emulate a user running cscript or wscript to run a local VisualBasic script that will download a file (but, of course,  could do any number of other malicious things).

### Proposal
I have written a test for each, tested it, and integrated it into my local clone of the ART master.

### References
https://lolbas-project.github.io/lolbas/Binaries/Cscript/
https://lolbas-project.github.io/lolbas/Binaries/Wscript/

### Code snippet from T1105.yaml
`- name: Download a file using wscript 
  description: |
    Use wscript to run a local VisualBasic file to download a remote file
  supported_platforms:
  - windows
  input_arguments:
    vbscript_file:
      description: Full path to a VisualBasic file that does the download work
      type: Path
      default: PathToAtomicsFolder\T1105\src\T1105-download-file.vbs
  executor:
    command: |
      wscript.exe #{vbscript_file}
    name: command_prompt
    
- name: Download a file using cscript
  description: |
    Use cscript to run a VisualBasic file to download a remote file
  supported_platforms:
  - windows
  input_arguments:
    vbscript_file:
      description: Full path to a VisualBasic file that does the download work
      type: Path
      default: PathToAtomicsFolder\T1105\src\T1105-download-file.vbs
  executor:
    command: |
      cscript.exe #{vbscript_file}
    name: command_prompt`

### Contents of the VisualBasic file:
`Set objWinHttp = CreateObject("WinHttp.WinHttpRequest.5.1")
URL = "https://raw.githubusercontent.com/redcanaryco/atomic-red-team/master/LICENSE.txt"
objWinHttp.open "GET", URL, False
objWinHttp.send ""
`

**Comment by clr2of8** [comment]
This is cool!  It looks like you wrote two atomic tests. I'd love to see you submit a PR for these and get your free T-shirt from Red Canary. Connect with me on the Atomic Red Team slack works space, (I'm @OrOneEqualsOne on slack there) and I can walk you through it.

**Comment by MSAdministrator** [comment]
I believe this issue can be closed. Please open it back up if I am wrong.
