### ISSUE TITLE
COM Hijacking Test (previously T1122) missing

### ISSUE THREAD

**Issue by zaicurity** [redcanaryco/atomic-red-team#1617]
Hello,
I noticed that a previously existing test for COM Hijacking (back then T1122) https://github.com/redcanaryco/atomic-red-team/pull/969 is no longer available in the master branch. The ID for this technique was changed from T1122 to T1546.015 but there are currently no tests under either of those.

Since I cannot find any commits mentioning the test's removal I'm wondering if it got lost when the technique ID changed. If so, would it be possible to move the test to T1546.015?
I ran the "COM Hijack Leveraging .NET profiler DLL" test (https://raw.githubusercontent.com/redcanaryco/atomic-red-team/9b73020cee2ee860dc9d79effde0e32b0e8e9567/atomics/T1122/T1122.yaml) and it seemed to work fine.

**Comment by amashinchi-rc** [comment]
Hi @zaicurity, and thank you for noting this!

At a glance, it appears these tests were moved to [1574.012](https://github.com/redcanaryco/atomic-red-team/tree/master/atomics/T1574.012). 

Are those the tests you were looking for?

**Comment by zaicurity** [comment]
The first test in there is indeed the one I was looking for. Thank you for looking into it!
