### ISSUE TITLE
Problem: An alarm is generated after atom execution.

### ISSUE THREAD

**Issue by muguangzhuri** [redcanaryco/atomic-red-team#1680]
## What did you do?

Invoke-AtomicTest T1548.002

## What did you expect to happen?
Executing test: T1059.003-1 Create and Execute Batch Script
Done executing test: T1059.003-1 Create and Execute Batch Script

## What happened instead?

The alarm: [C:\AtomicRedTeam\atomics\T1548.002\T1548.002.yaml][Atomic test name: Bypass UAC using Event Viewer (cmd)] The 
following input argument is defined but not utilized: 'executable_binary'.
The alarm: [C:\AtomicRedTeam\atomics\T1548.002\T1548.002.yaml][Atomic test name: Bypass UAC using Event Viewer (PowerShell)]
 The following input argument is defined but not utilized: 'executable_binary'.
The alarm: [C:\AtomicRedTeam\atomics\T1548.002\T1548.002.yaml][Atomic test name: Bypass UAC using Fodhelper] The following 
input argument is defined but not utilized: 'executable_binary'.
The alarm: [C:\AtomicRedTeam\atomics\T1548.002\T1548.002.yaml][Atomic test name: Bypass UAC using Fodhelper - PowerShell] 
The following input argument is defined but not utilized: 'executable_binary'.
The alarm: [C:\AtomicRedTeam\atomics\T1548.002\T1548.002.yaml][Atomic test name: Bypass UAC using ComputerDefaults 
(PowerShell)] The following input argument is defined but not utilized: 'executable_binary'.
The alarm: [C:\AtomicRedTeam\atomics\T1548.002\T1548.002.yaml][Atomic test name: Bypass UAC by Mocking Trusted Directories] 
The following input argument is defined but not utilized: 'executable_binary'.
The alarm: [C:\AtomicRedTeam\atomics\T1548.002\T1548.002.yaml][Atomic test name: Bypass UAC using sdclt DelegateExecute] The
 following input argument is defined but not utilized: 'command.to.execute'.
Executing test: T1548.002-1 Bypass UAC using Event Viewer (cmd)
Done executing test: T1548.002-1 Bypass UAC using Event Viewer (cmd)
Operation completed successfully

## Your Environment

* Windows 10 64-bit

**Comment by clr2of8** [comment]
Thanks for reporting. I just tested this with the latest version of atomic red team and this is not longer an issue. I am closing this for now but if you update to the latest and still find an issue please not it here. Thx
