### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by jeffmcjefferson** [redcanaryco/atomic-red-team#1683]
First off - amazing work on this! Thanks for it all! Normally I wouldn't even bring it up but I can't unsee it and I keep looking at it XD

There are two misspellings of "execution" on this page https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1087.001/T1087.001.md

Under section Atomic Test #8 in that first line: "Enumerate all accounts Upon **exection**"

Under section Atomic Test #10 in that first line: "Enumerate logged on users. Upon **exeuction**"

That is all. Thanks again! :)

**Comment by clr2of8** [comment]
Thanks for noted it. I'm the same way about typo's, the bug me like crazy. Keep it up.
