### ISSUE TITLE
T1003 IWR GetPrereqs error

### ISSUE THREAD

**Issue by frack113** [redcanaryco/atomic-red-team#1699]
## What did you do?
![image](https://user-images.githubusercontent.com/62423083/147480067-3ca70696-522b-4b80-a1ec-a56cdefe0a1c.png)

## What did you change ?
T1003.yaml
```yaml
IEX(IWR "https://raw.githubusercontent.com/redcanaryco/invoke-atomicredteam/master/Public/Invoke-WebRequestVerifyHash.ps1" -UseBasicParsing)
```
![image](https://user-images.githubusercontent.com/62423083/147480210-1f3badf8-b3aa-4a94-ab74-339b1f02114e.png)

**Comment by clr2of8** [comment]
fixed in pr #1702 , thx
