### ISSUE TITLE
T1204.002 test 8 errors

### ISSUE THREAD

**Issue by frack113** [redcanaryco/atomic-red-team#1705]
When run Potentially Unwanted Applications (PUA) {02f35d62-9fdc-4a97-b899-a5d9a876d295} 
![image](https://user-images.githubusercontent.com/62423083/147869360-5ff57b34-e50d-4310-96c9-3ccd8559d7a4.png)

I have to kill the pop-up by hand to cleanup so I have change:
```yaml
    cleanup_command: |
      Remove-Item #{pua_file} -ErrorAction Ignore
```
to 
```yaml
    cleanup_command: |
      Stop-Process -name PotentiallyUnwanted
      Remove-Item #{pua_file} -ErrorAction Ignore
```

But can find the art-out.txt cause.

Nota: test 7 Headless Chrome code execution via VBA add a cleanup_command part
```yaml
    cleanup_command: |
      Stop-Process -name mshta
```

**Comment by clr2of8** [comment]
Thanks for the report. Pull request merged.
