### ISSUE TITLE
T1566.001 Download Phishing Attachment - VBScript

### ISSUE THREAD

**Issue by frack113** [redcanaryco/atomic-red-team#1712]
Hello,
I don't see if this test is usefull or broken
The test : 
`The macro-enabled Excel file contains VBScript which opens your default web browser and opens it to google.com. The below will successfully download the macro-enabled Excel file to the current location. File is downloaded to the %temp% folder.`

what is the purpose  :  
- Detect the dowload file
The test don't need excel

- Detect excel starting a exe by VBScript
Excel is never lauch so the test is broken

Thanks

**Comment by clr2of8** [comment]
Thanks for the report. Pull request merged.
