### ISSUE TITLE
Invoke-ATHCompiledHelp : The HH executable supplied is not hh.exe

### ISSUE THREAD

**Issue by frack113** [redcanaryco/atomic-red-team#1714]
## What did you do?
I run T1218.001 test

## What did you expect to happen?
Open the Compiled HTML File

## What happened instead?
![image](https://user-images.githubusercontent.com/62423083/148677995-2d1c46e5-d8f7-416d-b832-b92bbafbedf7.png)

## Your Environment
Windows 10 21H2
hh.exe exist in `c:\Windows`
Test 1 and 2 works well.

**Comment by frack113** [comment]
find  [check InvokeCompiledHTMLFile.ps1](https://github.com/redcanaryco/AtomicTestHarnesses/blob/5dc5095a3f718af43e56f68067d8c0d0147f8436/TestHarnesses/T1218.001_CompiledHTMLFile/InvokeCompiledHTMLFile.ps1#L234)
Works only for eng version so change to 
`if ($HHFileInfo.VersionInfo.ProductName -ne 'HTML Help') and ($HHFileInfo.VersionInfo.ProductName -ne 'Aide HTML'){`
and get my 
![image](https://user-images.githubusercontent.com/62423083/148800245-58e7aaae-d8aa-4049-a36e-2695a27e397c.png)

**Comment by frack113** [comment]
Hi
The `Invoke-ATHCompiledHelp` works only on english windows
Change
```
    if ($HHFileInfo.VersionInfo.ProductName -ne 'HTML Help') {
        Write-Error "The HH executable supplied is not hh.exe: $HHFullPath"

        return
    }
```
to
```
    if ($HHFileInfo.VersionInfo.ProductName -ne 'Aide HTML') {
        Write-Error "The HH executable supplied is not hh.exe: $HHFullPath"

        return
    }
```

get 
![image](https://user-images.githubusercontent.com/62423083/148813358-c361c893-9a57-4cba-bf1e-40f12f941699.png)

**Comment by clr2of8** [comment]
@frack113 Can you submit a PR to allow this to work for both language versions? Then I can approve.

**Comment by frack113** [comment]
@clr2of8 it is done.

**Comment by clr2of8** [comment]
Ah, I didn't realize that the proposed change was to be against a separate repository. I'll close out this issue here. Thx for submitting that.
