### ISSUE TITLE
Problem: Unable to trigger T1562.008 using atomic-operator

### ISSUE THREAD

**Issue by esanyaCode** [redcanaryco/atomic-red-team#1736]
## What did you do?
atomic-operator run --techniques T1562.008

## What did you expect to happen?
It should trigger aws event wrt T1562.008 
It should trigger aws cloudtrail event.

## What happened instead?
I got the below error.
"""""""""""""""""'
(env) esanya@WINffL8zIwCujun:~/my_code/atomic-operator$ atomic-operator run --techniques T1562.008
2022-01-21 22:21:16,350 - Base.AtomicOperator - INFO - Running AWS CloudTrail Changes test (9c10dc6b-20bd-403a-8e67-50ef7d07ed4e) for technique T1562.008
2022-01-21 22:21:16,700 - Base.Runner - INFO -

Output: aws-cli/1.18.69 Python/3.8.10 Linux/5.10.60.1-microsoft-standard-WSL2 botocore/1.16.19

2022-01-21 22:21:18,123 - Base.Runner - INFO -

Output: usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

 aws help
 aws <command> help
 aws <command> <subcommand> help
aws: error: argument --name: expected one argument
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

 aws help
 aws <command> help
 aws <command> <subcommand> help
aws: error: argument --name: expected one argument
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

 aws help
 aws <command> help
 aws <command> <subcommand> help
aws: error: argument --name: expected one argument
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

 aws help
 aws <command> help
 aws <command> <subcommand> help
aws: error: argument --name: expected one argument

9c10dc6b-20bd-403a-8e67-50ef7d07ed4e: {"localhost": {"command": {"output": "usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]\nTo see help text, you can run:\n\n aws help\n aws <command> help\n aws <command> <subcommand> help\naws: error: argument --name: expected one argument\nusage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]\nTo see help text, you can run:\n\n aws help\n aws <command> help\n aws <command> <subcommand> help\naws: error: argument --name: expected one argument\nusage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]\nTo see help text, you can run:\n\n aws help\n aws <command> help\n aws <command> <subcommand> help\naws: error: argument --name: expected one argument\nusage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]\nTo see help text, you can run:\n\n aws help\n aws <command> help\n aws <command> <subcommand> help\naws: error: argument --name: expected one argument\n"}}, "technique_id": "T1562.008", "technique_name": "Impair Defenses: Disable Cloud Logs"}
"""""""""""""""""""""""""""""""""""""""""""""""""""""

## Your Environment

* Which *specific* operating system are you running (e.g. Windows 7 SP1 32-bit)?
* Linux
* Did you run the test from an elevated or root prompt?
* Yes
* If relevant, which atomic test is this specific to?
* T1562.008
* If relevant, which [execution harness](2) are you attempting to use?

[1]: https://github.com/redcanaryco/atomic-red-team/tree/master/atomics "atomic tests"
[2]: https://github.com/redcanaryco/atomic-red-team/tree/master/execution-frameworks "execution frameworks"

**Comment by clr2of8** [comment]
@patel-bhavin can you check whether this is an issue with the atomic test itself or only with the atomic operator executor?

**Comment by patel-bhavin** [comment]
@esanyaCode :  I am getting the same error when i try your command. 

I also tried to execute another AWS atomic, `atomic-operator run --techniques T1136.003` and i get a similar error
![image](https://user-images.githubusercontent.com/7771446/151269600-ff8686c0-1e96-40b7-89ed-3674bb4ac419.png)

This makes me think that this error is on the atomic-operator executor

**Comment by clr2of8** [comment]
@patel-bhavin confirmed that the atomic test works as is with Invoke-AtomicRedTeam. @esanyaCode I'm going to close this issue in this repository, could you re-open in the Atomic Operator repository instead.
