### ISSUE TITLE
Problem: T1027.004 -TestNumbers 1

### ISSUE THREAD

**Issue by victormonga** [redcanaryco/atomic-red-team#1792]
Output of this test is not expected.

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/70647502/155828966-c85954bd-9f20-499a-a71b-f1e1c5bf1d42.png">

**Comment by clr2of8** [comment]
The output looks correct to me. If you check for the existing of this file C:\Windows\Temp\T1027.004.exe after running the test, do you see it? Is there some other output you are expecting?
