### ISSUE TITLE
Problem: T1112 test 10

### ISSUE THREAD

**Issue by frack113** [redcanaryco/atomic-red-team#1817]
When run the T1112 test  10 the Cmd is disable.
So the `command_prompt` executor do not works anymore

Solution : 
 - Change to
```
executor:
    command: |
      reg add "HKEY_CURRENT_USER\Software\Policies\Microsoft\Windows\System" /v "DisableCMD" /t REG_DWORD /d "1" /f
      reg delete "HKEY_CURRENT_USER\Software\Policies\Microsoft\Windows\System" /v "DisableCMD" /f 
```
- change the test to powershell executor

**Comment by clr2of8** [comment]
Good catch. I'll watch for you next PR, wink wink.
