### ISSUE TITLE
T1562.001 Disable Windows Defender Tamper Protection TamperData key

### ISSUE THREAD

**Issue by frack113** [redcanaryco/atomic-red-team#1846]
## What did you do?
I have run [T1562.001](https://github.com/redcanaryco/atomic-red-team/blob/bbe0da2d8a4f958f0837149dee1c4289da3a2c7f/atomics/T1562.001/T1562.001.md) test 28 and reboot the Windows 10 VM

## What did you expect to happen?
Tamper Protection to be disabled

## What happened instead?
Tamper Protection is allways enable.

## Your Environment
Windows 10 x64 last update/KB installed.
I did not find any clue of `TamperData` keys on internet except the ref.
Find many time `TamperProtection` even get a  [Sigma rule for tamper](https://github.com/SigmaHQ/sigma/blob/dd7576e4b34058061769941b51ff3e8f3e19d68b/rules/windows/registry_set/registry_set_disabled_tamper_protection_on_microsoft_defender.yml)

Before update the detection rule , If some can validate the `TamperData` .
Thanks

**Comment by clr2of8** [comment]
We will look into it. Thank you!

**Comment by clr2of8** [comment]
Test was removed in PR #1860
