### ISSUE TITLE
Idea: Add a new field to the YAML files for the tests that need an minimum user interaction for completion 

### ISSUE THREAD

**Issue by Alrios** [redcanaryco/atomic-red-team#1920]
### Use-cases

Using the atomic-red-team for automated pentesting can be difficult because some tests that are not have the executor as "manual", they still need some user interaction for the completion. Running the atomic tests for the technique T1548.003 on Linux, the first test ***Sudo usage*** has the following commands:
```
sudo -l      
sudo cat /etc/sudoers
sudo vim /etc/sudoers
```
The last command opens vim, but the program will still be running until the user decide manually to close the program, which is an obstacle if one tries to automate the atomic tests.

### Proposal

I have an idea for a solution, the first one is to add an extra field to the tests that requires a minimum of user interaction, like;
```
    ....
    user_interaction : yes
    executor : sh
   ....
```
So for the people that tries to do an automation of the atomic tests, can filter which tests require a minimal of user interaction and skip them. One can also edit the mayority of the tests to make them user interation free, but for the ones that are imposible to change just add the new field of ***user_interaction***.

**Comment by packetzero** [comment]
I second this.  I want to move towards automating ATR, and need to programmatically filter out tests that need user interaction.

**Comment by clr2of8** [comment]
I like the idea. I wonder if your sudo example would really need to be marked as "requires interaction" since the attacker behavior is able to complete but the process is left hanging because vim doesn't close. This could be handled by the execution framework via a timeout, allowing automation to continue. ([Invoke-AtomicRedTeam](https://github.com/redcanaryco/invoke-atomicredteam/wiki/Execute-Atomic-Tests-(Local)#specify-a-process-timeout) has this implemented). But to your point, yes there are some tests that require user action to complete the intended attack emulation. Thoughts?

**Comment by packetzero** [comment]
I didn't know that the timeout was an option in the Invoke runner.  I will have to see how hard it is to add to the `go-atomicredteam` that I use for macOS and linux.  

I suppose his script could also start the `vim` in background (if on unix) and kill if still exists.  It would be nice to have the tests flagged though.  Imagine if there is no X-windows / Desktop login session , it will take over the terminal?  To follow naming convention set forth by `elevation_required`, maybe this flag can be `user_interaction_required` ?

Not to be confused with `uac_required`, which I think is also needed for a different use-case...   the user is prompted to click OK or authenticate to allow action.  On MacOS, this could be a TCC prompt to allow access to audio device, or user must authenticate to allow a 'drag application to trash' action.
