### ISSUE TITLE
Problem: Grammar error on T1558.003.md 

### ISSUE THREAD

**Issue by LauraB19** [redcanaryco/atomic-red-team#1926]
## What did you do?

On [this](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1558.003/T1558.003.md) doc, there is a minor grammar issue as denoted in **bold** in the excerpt below:

> Adversaries possessing a valid Kerberos ticket-granting ticket (TGT) may request one or more Kerberos ticket-granting service (TGS) **service** tickets for any SPN from a domain controller (DC).

## What did you expect to happen?

The fix is to simply get rid of the second "service" in that sentence. A totally minor issue that I came across while conducting

## What happened instead?

Redundancy in the sentence.

**Comment by clr2of8** [comment]
Hi LauraB19, we appreciate you giving feedback on this project! The particular part of the file you reference is actually dynamically generated copy of what is published on the Mitre Att&ck website for the Technique so any updates/fixes to it would have to be made in the source repository. I'm going to close out the issue on our side but please keep contributing in the future.
