### ISSUE TITLE
Problem: T1569.002 syntax issue?

### ISSUE THREAD

**Issue by Paul-McD** [redcanaryco/atomic-red-team#1988]
## What did you do?

ℹ cloned and built caldera w/atomic plugin enabled

## What did you expect to happen?

ℹ Caldera to run

## What happened instead?

ℹ Caldera Atomic Service enters infinite loop trying to import (https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1569.002/T1569.002.yaml)

Reviewing https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1569.002/T1569.002.yaml, was modified April 14th, which is when we began experiencing the problem. Appears the new section is missing "auto_generated_guid". 

I have not proven this is the problem but is suspicious. Using the previous version of the file Caldera/Atomic works as expected

## Your Environment

not relevant

**Comment by Paul-McD** [comment]
I was looking at the wrong version of the file, it does have a guid. However, this is the underlying behavior
![image](https://user-images.githubusercontent.com/106769603/171726990-624c9512-1295-431d-8249-d0be66d5c51b.png)

**Comment by clr2of8** [comment]
Hi Paul, I appreciate your efforts in writing this up so well with screenshots and all but I think posting this as an issue in [CALDERA's github](https://github.com/mitre/caldera/issues) will be a better fit.
