### ISSUE TITLE
Idea: Add tests for T1547/003 addition of time providers

### ISSUE THREAD

**Issue by tbennett6421** [redcanaryco/atomic-red-team#1991]
### Use-cases

I'm unsure if this is the correct template or not. Should this be Idea or Test?

No test exists in the repo to support privesc/persistence via the time providers. This is an important test that can be used to obtain privilege escalation or install an implant for persistence.

### Proposal
Ideally we should create a test for the following

Adding a dll to the following reg key: `HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\W32Time\TimeProviders\`
and restarting the time service.

### References
https://attack.mitre.org/techniques/T1547/003/
https://stmxcsr.com/persistence/time-provider.html

Happy to add a test, if/when I have the resources

**Comment by tr4cefl0w** [comment]
Working on the DLL at the moment, I can write the test too when it's ready. Just note that the DLL is not directly added under TimeProviders. The subkey is the name of the provider and can be arbitrary. In the subkey, the `DllName` value will contain the path to the DLL.
