### ISSUE TITLE
UAC Bypass

### ISSUE THREAD

**Issue by underneith** [redcanaryco/atomic-red-team#2]
https://github.com/hfiref0x/UACME

Might be worth including those in your UAC testing suite.

**Comment by caseysmithrc** [comment]
For sure, that is an excellent collection.  When we reviewed that tactic, we felt that there is already a reference here: https://attack.mitre.org/wiki/Technique/T1088 .  I agree its an excellent set of test, I'm not quite sure how to incorporate it yet.  Let me think about that.  I'll keep this open until we can come to agreement on best way to include this.

**Comment by caseysmithrc** [comment]
We agree https://github.com/hfiref0x/UACME is a comprehensive testing tool.  For now we have decided to leave it out of the repo since it is a binary. But I encourage people to explore that repo it has the most up to date information on UAC bypasses.
