### ISSUE TITLE
Problem: T1552.004/Failed to remove directory

### ISSUE THREAD

**Issue by danf42** [redcanaryco/atomic-red-team#2006]
## What did you do?
Run cleanup for test T1552.004 Test number 3 'Copy Private SSH Keys with CP' against a Linux host

## What did you expect to happen?
Remove the directory '/tmp/art-staging'

## What happened instead?
Failed to remove the directory `rm: cannot remove '/tmp/art-staging': Is a directory `

The cleanup command for T1552.004 #3 is `rm #{output_folder}`.  It should be `rm -rf #{output_folder}`

## Your Environment

* Which *specific* operating system are you running (e.g. Windows 7 SP1 32-bit)? Debian 11
* Did you run the test from an elevated or root prompt? No
* If relevant, which atomic test is this specific to? T1552.004 Test number 3 'Copy Private SSH Keys with CP'
* If relevant, which [execution harness](2) are you attempting to use?

[1]: https://github.com/redcanaryco/atomic-red-team/tree/master/atomics "atomic tests"
[2]: https://github.com/redcanaryco/atomic-red-team/tree/master/execution-frameworks "execution frameworks"

**Comment by clr2of8** [comment]
Thank you for the nice issue write-up. I've made a PR with the proposed fix. Are you interested in contributing fixes yourself in the future? We have contributing guide [here on the Wiki](https://github.com/redcanaryco/atomic-red-team/wiki/Contributing) and also [this YouTube video](https://www.youtube.com/watch?v=5MCtee8_s24) shows a very easy way to make changes like this. Plus, you get a free Atomic Red Team tshirt for your first contribution!

**Comment by clr2of8** [comment]
fix is in place

**Comment by danf42** [comment]
Thanks for the links on contributing to the project!
