### ISSUE TITLE
Problem: a mistake in T1112 description

### ISSUE THREAD

**Issue by rezbrz** [redcanaryco/atomic-red-team#2062]
## **Invoke-AtomicTest T1112 -TestNumbers 2**
when I wanted to run the above command, I reviewed the T1112.yaml file and understood there is misleading issue in the description part of the testnumbr. It is said: "Additionally, open Registry Editor to view the modified entry in HKCU\Software\Microsoft\Windows\CurrentVersion\Run." but this test case is not related to the mentioned registry. So, I believe the description part should be corrected and changes to "HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run"

**Comment by clr2of8** [comment]
Thanks for noticing and reporting.  Are you up for making this edit yourself? I've got a short video tutorial [here](https://youtu.be/5MCtee8_s24) on how to do it. It's pretty easy.

**Comment by clr2of8** [comment]
I don't see the issue in the file currently so closing this issue out for now.
