### ISSUE TITLE
Problem: Issue in executing T1218.001 Usecases for remote execution .chm file is not executing remotely

### ISSUE THREAD

**Issue by testuser335** [redcanaryco/atomic-red-team#2074]
Hello Team,

we have installed AtomicTestHarnesses on remote machine and tried to execute Atomic red team technique T1218.001  3rd,4th,5th,6th and 7th usecases on remote execution. but facing issue while creating new child process and getting error powershell.exe cannot be spawned error" might be some issue in .chm file is not able to open remotely so not able to create new process using InvokeCompiledHTMLFile.ps1
Could you please suggest some solution.

**Comment by MSAdministrator** [comment]
@testuser335 Have you created an issue in the AtomicTestHarness repository ? https://github.com/redcanaryco/AtomicTestHarnesses
