### ISSUE TITLE
Linux Indexes contains more than Linux tests

### ISSUE THREAD

**Issue by Thog** [redcanaryco/atomic-red-team#2130]
Linux Indexes contains tests that doesn't target Linux.

One example of it is [office-365-Disable-AntiPhishRule](https://github.com/redcanaryco/atomic-red-team/blob/6bd4bb42361532ac545967822f59ceae2ef4943a/atomics/T1562.001/T1562.001.md#atomic-test-25---office-365-disable-antiphishrule) being listed [in the CSV index](https://github.com/redcanaryco/atomic-red-team/blob/6bd4bb42361532ac545967822f59ceae2ef4943a/atomics/Indexes/Indexes-CSV/linux-index.csv#L70) and Mardown index.

From a quick look it seems that the doc generator uses ``/^(?!windows|macos).*$/`` for [CSV](https://github.com/redcanaryco/atomic-red-team/blob/6bd4bb42361532ac545967822f59ceae2ef4943a/bin/generate-atomic-docs.rb#L54) and [Markdown](https://github.com/redcanaryco/atomic-red-team/blob/6bd4bb42361532ac545967822f59ceae2ef4943a/bin/generate-atomic-docs.rb#L44) generation.

Any reasons why this isn't ``/linux/`` to follow the same pattern as every other platforms?

**Comment by clr2of8** [comment]
Looks like we got it fixed. Thank you!
