### ISSUE TITLE
windows-collection-input capture missing file

### ISSUE THREAD

**Issue by carnal0wnage** [redcanaryco/atomic-red-team#22]
404 on 
https://github.com/redcanaryco/atomic-red-team/blob/master/Windows/Collection/Payloads/Collection/Get-keystrokes.ps1

should be:
https://github.com/redcanaryco/atomic-red-team/blob/master/Windows/Payloads/Collection/Get-Keystrokes.ps1

**Comment by MHaggis** [comment]
Thank you, @carnal0wnage! Got this fixed up.
