### ISSUE TITLE
Problem: T1082 list linux kernel modules should not require sudo

### ISSUE THREAD

**Issue by packetzero** [redcanaryco/atomic-red-team#2233]
## What did you do?

The test "Linux List Kernel Modules" in T1082.yaml uses `sudo`.  Not only is this not required, the test does not specify `elevation_required: true`.

## What did you expect to happen?

I just tested on Ubuntu 20.04 as regular user and I am able to enumerate the loaded kernel modules without sudo.
<img width="535" alt="image" src="https://user-images.githubusercontent.com/20775507/202012549-90e709cc-970d-498c-8564-a109d037235b.png">

## What happened instead?

no sudo needed.

## Your Environment

ubuntu 20.04 VM

**Comment by MSAdministrator** [comment]
I believe this has been resolved. Closing but please reopen if this was a mistake.
