### ISSUE TITLE
Problem: T1053.005 - "cleanup command" instead of "cleanup_command"

### ISSUE THREAD

**Issue by akivashor** [redcanaryco/atomic-red-team#2278]
## What did you do?

ℹ Please replace this with what you did.
I used the python atomic-operator package to load all of the atomics and while trying to parse this atomic I got this error:
AtomicExecutor.__init__() got an unexpected keyword argument 'cleanup command'

## What did you expect to happen?

I expected there to be an "cleanup_command" key

## What happened instead?

There was a "cleanup command" key which is probably a typo
## Your Environment

* Which *specific* operating system are you running (e.g. Windows 7 SP1 32-bit)? Windows10 64bit
* Did you run the test from an elevated or root prompt? No
* If relevant, which atomic test is this specific to? T1053.005
* If relevant, which [execution harness](2) are you attempting to use?

[1]: https://github.com/redcanaryco/atomic-red-team/tree/master/atomics "atomic tests"
[2]: https://github.com/redcanaryco/atomic-red-team/tree/master/execution-frameworks "execution frameworks"

**Comment by clr2of8** [comment]
Fixed, thank you!
