### ISSUE TITLE
Problem: T1564 Test #4 Cleanup 

### ISSUE THREAD

**Issue by zaicurity** [redcanaryco/atomic-red-team#2378]
## What did you do?

Ran `Invoke-AtomicTest T1564 -TestNumbers 4` which worked fine and then tried to run cleanup `Invoke-AtomicTest T1564 -TestNumbers 4 -Cleanup` which failed.
![image](https://user-images.githubusercontent.com/59199225/226316219-5c2d367a-75a1-41c9-8c99-e138e89659cd.png)
The return **Access is denied.** indicates that permissions on the modified (hidden) service prevent its deletion.

## What did you expect to happen?
Running `Invoke-AtomicTest T1564 -TestNumbers 4 -Cleanup` should delete the **AtomicService** service.

## What happened instead?
The cleanup returns **Access is denied.**

The **AtomicService** is still present on the system. While finding the service through a listing won't work, due to the fact that it was hidden, its presence can be confirmed by directly attempting to query it.

Below you can see the difference between querying the hidden service and a service which does not exist.
![image](https://user-images.githubusercontent.com/59199225/226317489-980fe8b2-fe3b-4685-ba8d-383850dd08e3.png)

The reason for this appears to be that the ACL setting, which hides the service from enumeration, also forbids its removal.

## Your Environment
* OS: Microsoft Windows 10 Pro (10.0.19045 N/A Build 19045)
* Ran tests with admin privileges
* Execution Framework: Invoke-AtomicTest

## Proposed fix
Add the following line at the top of the cleanup to configure the service ACL to allow the service removal.

`sc sdset #{service_name} "D:(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;IU)(A;;CCLCSWLOCRRC;;;SU)S:(AU;FA;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;WD)"`

With that change the cleanup works:
![image](https://user-images.githubusercontent.com/59199225/226319756-9ca9d7fd-ebb4-423b-ae8d-9097bed27772.png)

**Comment by burning-pm** [comment]
Thank you @zaicurity for filing the issue and providing a fix! We have pushed an update and it has been merged. Please let us know if you run into any issues with the update.
