### ISSUE TITLE
Main page example does not work

### ISSUE THREAD

**Issue by tfriesen** [redcanaryco/atomic-red-team#238]
The example test on the main page does not work. The URL seems to be case-sensitive, and instead of:

https://raw.githubusercontent.com/redcanaryco/atomic-red-team/master/atomics/t1117/RegSvr32.sct

it should be

https://raw.githubusercontent.com/redcanaryco/atomic-red-team/master/atomics/T1117/RegSvr32.sct

(Tested on Windows 7)

**Comment by caseysmithrc** [comment]
Yup, we'll correct that.  Thanks

**Comment by brianebeyer** [comment]
Fixed in #239
