### ISSUE TITLE
Problem: T1055.003 Test #1 Cleanup

### ISSUE THREAD

**Issue by zaicurity** [redcanaryco/atomic-red-team#2385]
## What did you do?
Ran the test and cleanup: 
`Invoke-AtomicTest T1055.003 -TestGuids 578025d5-faa9-4f6d-8390-aae527d503e1`
`Invoke-AtomicTest T1055.003 -TestGuids 578025d5-faa9-4f6d-8390-aae527d503e1 -Cleanup`
![image](https://user-images.githubusercontent.com/59199225/227178388-f0473f1b-9e97-411e-920d-67f9abbaf364.png)

## What did you expect to happen?
Notepad is launched, then a MessageBox pops up. Then cleanup should stop the Notepad process.

## What happened instead?
The test itself worked. Notepad was launched and the MessageBox appeared. However, the cleanup was unable to close the Notepad process and displayed an error in Powershell.
The error indicates that the referenced `$notepad.pid` was null. This is the case because the variable `$notepad` is defined during the test and is not available during cleanup.
On my system I also noticed during testing that `$notepad.pid` is always empty, even during the test execution. I had to use `$notepad.id` instead to reference the PID.

## Your Environment
* OS: Microsoft Windows 10 Pro (10.0.19045 N/A Build 19045)
* Ran powershell with admin privileges
* Execution Framework: Invoke-AtomicTest

## Suggested Solution
Integrate the cleanup into the test itself where the $notepad variable can be referenced to stop the process. To make sure the technique is fully executed before cleanup a timeout of 10 seconds can be used. Please note the use of `$notepad.id` instead of `$notepad.pid`.

The updated test could look like this. It worked during my testing.
```
$notepad = Start-Process notepad -passthru
Start-Process $PathToAtomicsFolder\T1055.003\bin\InjectContext.exe
Start-Sleep -Seconds 10
Stop-Process $notepad.id
```
Alternative options I see would be to not have a cleanup at all or to run a cleanup which terminates all running notepad processes.

**Comment by clr2of8** [comment]
Great write-up! Thanks, addressed in PR #2406
