### ISSUE TITLE
Problem: atomic-git channel no longer receiving updates

### ISSUE THREAD

**Issue by keithmccammon** [redcanaryco/atomic-red-team#2411]
## What did you do?

Multiple contributors have committed, merged, or otherwise updated atomic-red-team and invoke-atomicredteam.

## What did you expect to happen?

We expect an update in the atomic-git Slack channel.

## What happened instead?

There was no update :(

The error logs show a 404. An example log can be found here: https://github.com/redcanaryco/atomic-red-team/settings/hooks/17529511

<img width="789" alt="faily-mcfailerson" src="https://user-images.githubusercontent.com/50701/236456751-496c44e3-c7ac-4415-b636-5f72dd08bb69.png">

**Comment by josehelps** [comment]
I think I just solved this :smile: see the slack.
