### ISSUE TITLE
Idea: New tests need to added to END of yaml

### ISSUE THREAD

**Issue by amalone-scwx** [redcanaryco/atomic-red-team#2416]
### Use-cases
I am slowly trying to upstream some changes made to a local fork of `atomic-red-team` repo, and came across an instance of a test added at the top of a file (`T1552.001`).  Given that tests in yaml files are often referenced by their index/offset in the file, this breaks any references to the test.
https://github.com/redcanaryco/atomic-red-team/commit/fdcca49a52ffb328a826770d61c198422439f44b

### Proposal
Pull Request reviewers will need to be aware when reviewing and catch them.  However, it should not be too hard to catch with a script in CI.

### References
Example of reference to changed T1552.001 test in automation criteria:
https://github.com/secureworks/atomic-validation-criteria/blob/master/linux/T1505-T1574_linux.csv#L186

**Comment by clr2of8** [comment]
We do like to keep similar tests in proximity to each other in the yaml files and this means that those handy tests numbers can change. For this reason, we have provided the `auto_generated_guid` as this will always remain the same for each atomic and can be used programmatically without fear of things changing as the order of atomics in the yaml file may change. Thank you for the feedback and hopefully adjusting your process to use the GUIDs will meet your needs going forward.
