### ISSUE TITLE
Adding msxsl.exe ...

### ISSUE THREAD

**Issue by MrThreat** [redcanaryco/atomic-red-team#248]
Afternoon

I have been using msxsl.exe lately and its been quite effective. I looked through all your red team stuff and couldn't find it. Below are some references for you, maybe you can add it to your lists.

- https://pentestlab.blog/tag/msxsl/
- https://twitter.com/subTee/status/877616321747271680
- https://www.virustotal.com/#/file/42987d5db98c59779831681cdabefb9622f9ab57ebf5bdb7354b74aac46512c8/community

> Anyways food for thought.

**Comment by MHaggis** [comment]
Thank you, @MrThreat . It's on the radar. We're waiting for MITRE to update and we will then get this added to the matrix.

**Comment by caseysmithrc** [comment]
I think we can add this as Trusted Developer Utilities
https://attack.mitre.org/wiki/Technique/T1127

Will merge once we have a test.  Closing issue for now.

**Comment by caseysmithrc** [comment]
This has been added to ATT&CK

https://attack.mitre.org/techniques/T1220/
