### ISSUE TITLE
Problem: Test GUID not generated after PR merged

### ISSUE THREAD

**Issue by hunty-dumpy** [redcanaryco/atomic-red-team#2496]
## What did you do?

See related pull request: https://github.com/redcanaryco/atomic-red-team/pull/2490
Test GUID not generated after code merge

## What did you expect to happen?

Get at test GUID added to the YAML after the merge to master

## What happened instead?

Guid didn't get added

**Comment by clr2of8** [comment]
Thank you. It looks like our automation that does that is broke and has been for 2 weeks. Working on the fix now.

**Comment by zaicurity** [comment]
Same happend for #2491. The new atomic also wasn't added to the .md file.

**Comment by clr2of8** [comment]
Thank you. We are still fighting a GitHub permission issue but should have it resolved soon. 👍
