### ISSUE TITLE
Dead Links - Linux Tests

### ISSUE THREAD

**Issue by echobb8** [redcanaryco/atomic-red-team#253]
In reviewing this page:

`https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/linux-index.md`

I found that nearly all the Lateral Movement tests (as well as others on the page) are pointed to a dead link:

`https://github.com/redcanaryco/atomic-red-team/blob/uppercase-everything/CONTRIBUTING.md`

**Comment by echobb8** [comment]
Looks like there are dead links here as well: `https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/macos-index.md`

**Comment by caseysmithrc** [comment]
Ok, Thanks we will get this corrected,  Thank you

**Comment by swelcher** [comment]
Just for confirmation, are you all manually updating these lists as a new atomic is approved through a PR? If not I can go through and update these links manually, or perhaps we could expand the automated script to update those hyperlinks upon a new atomic test, which I'm assuming could be possible?

**Comment by brianebeyer** [comment]
The -index files and matrices are automatically generated by the doc generation script run by the CI system. See #270 for what I believe fixes this.
