### ISSUE TITLE
Problem: T1048.002-1  

### ISSUE THREAD

**Issue by Rudy-RENOUX** [redcanaryco/atomic-red-team#2577]
Hello,
On powershell, this commande does not work: invoke-AtomicTest T1048.002-1 -GetPrereqs
There is 2 problems with get-prereq-commands:

Currently on Github
New-Item -Type Directory "PathToAtomicsFolder\..\ExternalPayloads\" -ErrorAction Ignore -Force | Out-Null
Invoke-WebRequest "https://curl.se/windows/dl-7.79.1/curl-7.79.1-win64-mingw.zip" -Outfile "PathToAtomicsFolder\..\ExternalPayloads\curl.zip"
Expand-Archive -Path "PathToAtomicsFolder\..\ExternalPayloads\curl.zip -DestinationPath" "PathToAtomicsFolder\..\ExternalPayloads\curl"
Copy-Item "PathToAtomicsFolder\..\ExternalPayloads\curl\curl-7.79.1-win64-mingw\bin\curl.exe" C:\Windows\System32\Curl.exe

Problem n°1: This url https://curl.se/windows/dl-7.79.1/curl-7.79.1-win64-mingw.zip is no longer accessible
Problem n°2: Expand-Archive cannot work because a double quote is misplaced after -DestinationPath

currently:
Expand-Archive -Path "PathToAtomicsFolder\..\ExternalPayloads\curl.zip -DestinationPath" "PathToAtomicsFolder\..\ExternalPayloads\curl"

After correction:
Expand-Archive -Path "PathToAtomicsFolder\..\ExternalPayloads\curl.zip" -DestinationPath "PathToAtomicsFolder\..\ExternalPayloads\curl"

-------------------------
Correction:
New-Item -Type Directory "PathToAtomicsFolder\..\ExternalPayloads\" -ErrorAction Ignore -Force | Out-Null
Invoke-WebRequest "https://curl.se/windows/dl-8.4.0_4/curl-8.4.0_4-win64-mingw.zip" -Outfile "PathToAtomicsFolder\..\ExternalPayloads\curl.zip"
Expand-Archive -Path "PathToAtomicsFolder\..\ExternalPayloads\curl.zip" -DestinationPath "PathToAtomicsFolder\..\ExternalPayloads\curl"
Copy-Item "PathToAtomicsFolder\..\ExternalPayloads\curl\curl-8.4.0_4-win64-mingw\bin\curl.exe" C:\Windows\System32\Curl.exe

**Comment by clr2of8** [comment]
Thank you for reporting so thoroughly. We got it updated. 👍
