### ISSUE TITLE
Problem: technique T1018 is throwing errors after the last update on the main branch 

### ISSUE THREAD

**Issue by Vjeroen** [redcanaryco/atomic-red-team#2583]
## What did you do?

 Invoke-AtomicTest -AtomicTechnique T1018 -TestNumbers 17
## What did you expect to happen?

Expected a list of domain computers 

Atomic needs to list domain computers 
## What happened instead?
**PS Error that states it executed technique 5 instead of 17:** 

Get-AtomicTechnique : [C:\AtomicRedTeam\atomics\T1018\T1018.yaml][Atomic test name:
Remote System Discovery - arp nix] 'atomic_tests[5].supported_platforms': 'freebsd'
must be one of the following: windows, macos, linux, office-365, azure-ad,              google-workspace, saas, iaas, containers, iaas:aws, iaas:azure, iaas:gcp.               At C:\AtomicRedTeam\invoke-atomicredteam\Public\Invoke-AtomicTest.ps1:343 char:71       + ... aml) { $AtomicTechniqueHash = Get-AtomicTechnique -Path $pathToYaml }             +                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                   + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-At

## Your Environment
Windows 10 

* Which *specific* operating system are you running (e.g. Windows 7 SP1 32-bit)? Windows 10 64bit
* Did you run the test from an elevated or root prompt? yes
* If relevant, which atomic test is this specific to? T1018 17
* If relevant, which [execution harness](2) are you attempting to use? 

[1]: https://github.com/redcanaryco/atomic-red-team/tree/master/atomics "atomic tests"
[2]: https://github.com/redcanaryco/atomic-red-team/tree/master/execution-frameworks "execution frameworks"

**Comment by cyberbuff** [comment]
Thanks for reporting the issue. Working on it now. Should be fixed within Nov 3.

**Comment by cyberbuff** [comment]
Should be fixed once #2585  and [#166](https://github.com/redcanaryco/invoke-atomicredteam/pull/166) are fixed.

**Comment by cyberbuff** [comment]
This should be fixed now
