### ISSUE TITLE
Problem: Duplicated `auto_generated_guid`

### ISSUE THREAD

**Issue by yoyocircle** [redcanaryco/atomic-red-team#2607]
## What did you do?

Parse the test yaml and index csv files.

## What did you expect to happen?

During parsing the yaml files, I found that the `auto_generated_guid` of two tests are duplicated. The newer one was created last week (#2587). The new test guid is same as the test "Dirty Vanity process Injection".

Here is [the reference](https://github.com/thomasxmeng/atomic-red-team/blob/master/atomics/T1055/T1055.yaml#L113-L164) for you.

Is this expected or the duplicated guid was filled by mistake?

## What happened instead?

N/A

## Your Environment

N/A

**Comment by thomasxmeng** [comment]
I did not delete that line where auto_generated_guid should be automatically generated.

**Comment by yoyocircle** [comment]
> I did not delete that line where auto_generated_guid should be automatically generated.

Oh okay, so it should be minor mistake and would fixed later? 😂

**Comment by thomasxmeng** [comment]
Thanks for spotting it. I believe the maintainer would delete this line.

**Comment by yoyocircle** [comment]
> Thanks for spotting it. I believe the maintainer would delete this line.

Cool, i am looking forward to the improvements!
