### ISSUE TITLE
Problem: Duplicate key in T1505.005.yaml

### ISSUE THREAD

**Issue by Rudy-RENOUX** [redcanaryco/atomic-red-team#2614]
Hello :-)

## What did you do?

ℹ Please replace this with what you did.
PS C:\Users\Administrator> Get-Item C:\AtomicRedTeam\atomics\T1505.005\T1505.005.yaml | Get-AtomicTechnique

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.

PS C:\Users\Administrator> Get-Item C:\AtomicRedTeam\atomics\T1505.005\T1505.005.yaml | Get-AtomicTechnique
attack_technique display_name                                     atomic_tests
---------------- ------------                                     ------------
{T1505.005}      Server Software Component: Terminal Services DLL {Simulate Patching termsrv.dll, Modify Terminal Services DLL Path}

## What happened instead?

ℹ Please replace this with of what happened instead.

PS C:\Users\Administrator> Get-Item C:\AtomicRedTeam\atomics\T1505.005\T1505.005.yaml | Get-AtomicTechnique
Get-AtomicTechnique : Exception calling "Load" with "1" argument(s): "Duplicate key"
At line:1 char:62
+ ... \AtomicRedTeam\atomics\T1505.005\T1505.005.yaml | Get-AtomicTechnique
+                                                       ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-AtomicTechnique

## Your Environment
Windows 2016 Server Standard
Run test with administrator privileges

-----------------------------------------------------------------------------------
To resolve problem, delete line 64 (elevation_required: true) in the file: ./atomics/T1505.005/T1505.005.yaml 

"elevation_required: true" is defined two times: lines 35 & 64 

Sincerely,
Rudy Renoux

**Comment by clr2of8** [comment]
Perfect, thank you. We fixed it up.

**Comment by clr2of8** [comment]
PS If you want to make this changes yourself in the future there is an easy way to do it from the web interface as shown on a demo video [here](https://github.com/redcanaryco/atomic-red-team/wiki/Contributing#open-a-pull-request)
