### ISSUE TITLE
Problem: Mismatch between available Atomic Tests for Linux and MITRE ATT&CK Layer

### ISSUE THREAD

**Issue by djelito-ps** [redcanaryco/atomic-red-team#2623]
We use the MITRE ATT&CK layers to systematically test our environments. There are techniques like T1204.002 (User Execution: Malicious File) that are marked as available for Linux in the ATT&CK layer, but taking a look into the documentation, these tests are only supported on Windows.

Cross-checking with "Invoke-AtomicTest T1204.002 -ShowDetailsBrief" on an AlmaLinux host also returns 0 applicable tests on this platform.
I assume this issue might exist regarding other techniques.

Thank you for your help!

**Comment by cyberbuff** [comment]
Hello @djelito-ps . Looking at the existing [Linux atomics](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/Indexes/Indexes-Markdown/linux-index.md), we currently don't have any atomics for the test you mentioned. That's the reason it doesn't show up any tests when you were trying to run it on your machine.

**Comment by djelito-ps** [comment]
Hello cuberbuff,
thank you for your answer. This is exactly as expected, but not the issue. The issue lies in the ATT&CK layers, which for example claim that there would exist a test for the mentioned atomic.
I have found at least one further example where this was the case, what leads me to the conclusion that there is a bigger issue with the layers.

<img width="460" alt="image" src="https://github.com/redcanaryco/atomic-red-team/assets/152259936/a9b8651f-1d50-4d6d-aa8a-f5c03574ac7f">

**Comment by cyberbuff** [comment]
Oh sorry about that. I misunderstood. I tried it with the [Atomic Layers that's on the repository](https://raw.githubusercontent.com/redcanaryco/atomic-red-team/master/atomics/Indexes/Attack-Navigator-Layers/art-navigator-layer-linux.json) and it didn't show any tests for User Execution. But the Layers from atomicredteam.io shows tests for User Execution. Are you using the layers from atomicredteam.io ?

**Comment by cyberbuff** [comment]
Yeah definitely. I can update them. Thanks for reporting the issue.

**Comment by djelito-ps** [comment]
Issue not resolved, old layer still on homepage.

**Comment by cyberbuff** [comment]
Hello. We are working on a new website which would have the new layers embedded in it. Sorry that this issue has been marked because it was stale for 30 days
