### ISSUE TITLE
Problem: Indexes/Indexes-CSV/windows-index.csv does not have T1547.015 entry

### ISSUE THREAD

**Issue by kchoudhury-scwx** [redcanaryco/atomic-red-team#2712]
## What did you do?
Was trying to execute the atomic test number 1 from T1547.015 technique in our Windows environment. 

## What did you expect to happen?
The atomic test number 1 from T1547.015 was expected to run.

## What happened instead?
The atomic test did not run as our framework relies on the /Indexes/Indexes-CSV/windows-index.csv file and there was no entry for T1547.015 in the windows-index.csv file even though this technique is present in the repo.

**Comment by clr2of8** [comment]
Thanks for bringing this to our attention. Those docs are generated with some Ruby code that is being replaced by new Python code in the next couple of weeks by one of our maintainers @cyberbuff  and we can make sure it is working again with the new code. Stay tuned!

**Comment by kchoudhury-scwx** [comment]
Thanks for the update.
