### ISSUE TITLE
Request: Adding predefined tags

### ISSUE THREAD

**Issue by dsolstad** [redcanaryco/atomic-red-team#2749]
It would be very helpful if test cases had predefined tags, as for example if the test needs local admin and where it should be ran from (domain controller, workstation, server etc). This way it's much easier to construct campaigns, especially when combined with Vectr.

**Comment by nshalabi** [comment]
> It would be very helpful if test cases had predefined tags, as for example if the test needs local admin and where it should be ran from (domain controller, workstation, server etc). This way it's much easier to construct campaigns, especially when combined with Vectr.
> 

Hi, check ATT&CK-TOOLS project and the ATT&CK View red team planning tool (disclosure: I am the author)
