### ISSUE TITLE
Problem: missing `auto_generated_guid`

### ISSUE THREAD

**Issue by yoyocircle** [redcanaryco/atomic-red-team#2753]
## What did you do?

Parsing the simulation from yaml files.

## What did you expect to happen?

There should be a `auto_generated_guid` for every simulation.

## What happened instead?

There is no `auto_generated_guid` for these simulations:
- Enumerate All Network Shares with SharpShares[[1]]
- Detect a Debugger Presence in the Machine [[2]]

## Your Environment

clone the repo from master branch.

[1]: https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1135/T1135.yaml#L184
[2]: https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1622/T1622.yaml#L4

**Comment by patel-bhavin** [comment]
@ljstella : Thanks for ID'ing the issue and fixing it. 

@yoyocircle : this issue should now be resolved and both those detections have auto_generated_guid now!Thank you.
