### ISSUE TITLE
Problem: Missing Invoke-AtomicRedTeam Module Files

### ISSUE THREAD

**Issue by kylaleppanen** [redcanaryco/atomic-red-team#2947]
## What did you do?

I cloned the Atomic Red Team repository and followed the installation instructions, but I cannot find the Invoke-AtomicRedTeam.psd1 or Invoke-AtomicRedTeam.ps1 files.

## What did you expect to happen?

I expected for the Invoke-AtomicRedTeam.psd1 or Invoke-AtomicRedTeam.ps1 files to have downloaded as they were supposed to.

## What happened instead?

The files did not download.

## Your Environment

* **Operating System**: macOS Monterey
* **Elevated Prompt**: No, I ran the commands in a standard terminal window.
* **Relevant Atomic Test**: Not applicable since the main module files are missing.
* **Execution Harness**: I am not using an execution harness as I cannot find the necessary module files.

[1]: https://github.com/redcanaryco/atomic-red-team/tree/master/atomics "atomic tests"
[2]: https://github.com/redcanaryco/atomic-red-team/tree/master/execution-frameworks "execution frameworks"

**Comment by cyberbuff** [comment]
Hello @kylaleppanen Sorry for the delay. `invoke-atomicredteam` is one of the executors that's in a separate repo . You can find the installation instructions here. https://github.com/redcanaryco/invoke-atomicredteam/wiki/Installing-Invoke-AtomicRedTeam Let me know if this works.
