### ISSUE TITLE
How to use it. How to simulate each attack.

### ISSUE THREAD

**Issue by DefenderLab** [redcanaryco/atomic-red-team#300]

**Comment by brianebeyer** [comment]
Hi @defenderlab, please provide further information so we can point you in the right direction. Have you started with https://atomicredteam.io/testing ?

**Comment by DefenderLab** [comment]
Do I need to copy each command from yaml file?  Or you have any script that parses yaml file and simulates the attack.

**Comment by MHaggis** [comment]
Hi @DefenderLab,
You can copy/paste them but it would require you to fill in any variables. Additionally, you can parse the YAML using any language you like. 
We also have a great powershell execution framework provided by Lee Holmes -
https://github.com/redcanaryco/atomic-red-team/tree/master/execution-frameworks

and a Ruby framework -
https://github.com/redcanaryco/atomic-red-team#bonus-apis-ruby-attck-api

Hope that helps!
