### ISSUE TITLE
No documentation or instructions to install at all

### ISSUE THREAD

**Issue by passwordleak** [redcanaryco/atomic-red-team#309]
Clicking on any of the links in the home page literally does nothing lol. Specifically of value: Quick Start: Using Atomic Red Team to test your security

Slack channel does not allow users to join: Contact the workspace administrator for an invitation

Seems like a great project and everything, but the documentation is literally nonexistant and so there is no way to use it. Sad.

**Comment by caseysmithrc** [comment]
There are also several references and resources here: 
http://atomicredteam.com
