### ISSUE TITLE
go-atomic.rb fatal error when creating report

### ISSUE THREAD

**Issue by fabamatic** [redcanaryco/atomic-red-team#313]
Hi, when executing a test in a windows system I get a failure on test report creation because the script tries to create a file with an invalid name:

`  - Writing results to atomic-test-executor-execution-2018-08-29T20:55:26Z.yaml

FATAL ERROR: Invalid argument @ rb_sysopen - atomic-test-executor-execution-2018-08-29T20:55:26Z.yaml`

**Comment by caseysmithrc** [comment]
Can you provide any additional details.  Which test are you trying to execute?

**Comment by fabamatic** [comment]
Happens with any test.  I narrowed the problem down to line 259 of go-atomic.rb.

`output_filename = "atomic-test-executor-execution-#{Time.now.utc.iso8601}.yaml"`

Time.now.utc.iso8601 returns a date with format "YYYY-MM-DDTHH:MM:SSZ", the semicolons are invalid as windows file name. My guess is that the time fetching method should be changed, but I am not proficient in ruby.

**Comment by fabamatic** [comment]
Using Ruby 2.4.4

**Comment by zacbrown** [comment]
@fabamatic - Thanks! That confirms my suspicion. I'll look at shuffling the format.

**Comment by zacbrown** [comment]
@fabamatic - This should be fixed as of PR #316.
