### ISSUE TITLE
Create NuGetApiKey for publishing Invoke-AtomicRedTeam to powershellgallery.com

### ISSUE THREAD

**Issue by zacbrown** [redcanaryco/atomic-red-team#345]
We need to create a NuGetApiKey for publishing Invoke-AtomicRedTeam to powershellgallery.com. This also requires an update for circleci YAML. 

Per Josh Rickard (MSAdministrator), he's provided an example AppVeyor configuration for this: 
https://github.com/MSAdministrator/PSNamedPipe/blob/master/appveyor.yml

**Comment by clr2of8** [comment]
Closing here since Invoke moved to a new repo
