### ISSUE TITLE
YAML Schema Modify - Add attribute to check if admin/root/required

### ISSUE THREAD

**Issue by caseysmithrc** [redcanaryco/atomic-red-team#371]
A question was posed in the Atomic Channel about checking wether or not a test requires admin (Windows ) or root privileges. 

I support this idea. Just need to think through where to put that check.
Update validation scripts
Retroactively update existing tests to have this added to all the existing test.

**Comment by brianebeyer** [comment]
I think we’d do this as a Boolean field inside the windows executor. 

What would you expect execution frameworks to do if they encountered that field being true?

**Comment by caseysmithrc** [comment]
I think we need Linux/Mac too, to incorporate root access/requirements

Executor's could be modified to check and filter to either include or exclude.

Executor's could also check current privileges and then branch based on true/false

**Comment by caseysmithrc** [comment]
I actually think since this already in the MITRE ATT&CK we could just pull in that attribute from the API.
"x_mitre_permissions_required": Attribute

**Comment by brianebeyer** [comment]
I don't think we can used `x_mitre_permissions_required` because that is more focused on the technique rather than the specific test command being executed.
