### ISSUE TITLE
Invoke-AtomicRedTeam - Get-AtomicTechnique

### ISSUE THREAD

**Issue by caseysmithrc** [redcanaryco/atomic-red-team#373]
# Report
There appears to be a bug in the Get-AtomicTechnique 

## What did you do?

 Get-AtomicTechnique -Path .\atomics\T1117\T1117.yaml

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    325      19     7604      25452       0.56   5652   1 ApplicationFrameHost
    158      10     6332      11480       0.73   9048   0 audiodg
    329      16     5212      20804       0.06   8380   1 backgroundTaskHost
    174      11     2048       8140       0.03    736   1 chrome
    142      11     1972       8780       0.03   5896   1 chrome

## What did you expect to happen?
I expected to create a test.  

## What happened instead?

The current state, it runs Get-Process and dies.

## Your Environment
Windows 10 x64 v1803

@rickardja if you have a chance can you check the code for the Get-AtomicTechnique method, or perhaps we need to update the documentation.  Thanks!

**Comment by MSAdministrator** [comment]
@caseysmithrc so sorry for missing this! I’ve been in paternity leave and wasn’t checking my email as frequently as I normally do.  Sorry again about that, but it looks like it was squared away. Thanks!!

**Comment by caseysmithrc** [comment]
@MSAdministrator Congrats!  No worries. I think we fixed it.  I'll actually close this now.  Hope all is well!
