### ISSUE TITLE
T1086 Atomic Test #6

### ISSUE THREAD

**Issue by TechOtaku2233** [redcanaryco/atomic-red-team#374]
# Report

T1086 Atomic Test #6 is false，The correct way is first execution $Password = Read-Host -AsSecureString，Then execution New-LocalUser -FullName 'full_name' -Name 'user_name' -Password $password -Description 'description'

and the true is Run it with powershell，not Run it with command_prompt，Your introduction is wrong.

## What did you do?

ℹ Please replace this with what you did.
New-LocalUser -FullName 'full_name' -Name 'user_name' -Password $password -Description 'description'

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.
Successfully created an account

## What happened instead?

ℹ Please replace this with of what happened instead.
error info:
New-LocalUser : 无法绑定参数“Password”。无法将“System.String”类型的“password”值转换为“System.Security.SecureStri
ng”类型。

## Your Environment

* Which *specific* operating system are you running (e.g. Windows 7 SP1 32-bit)?
win10 1709
* Did you run the test from an elevated or root prompt?
yes
* If relevant, which atomic test is this specific to?
T1086 Atomic Test #6

* If relevant, which [execution harness](2) are you attempting to use?
powershell

[1]: https://github.com/redcanaryco/atomic-red-team/tree/master/atomics "atomic tests"
[2]: https://github.com/redcanaryco/atomic-red-team/tree/master/execution-frameworks "execution frameworks"

**Comment by caseysmithrc** [comment]
Thank you @TechOtaku2233.  This as been corrected in https://github.com/redcanaryco/atomic-red-team/pull/401
Appreciate the feedback.
