### ISSUE TITLE
Consider "Variations" of each test

### ISSUE THREAD

**Issue by caseysmithrc** [redcanaryco/atomic-red-team#384]
# Report
Presently, each test is fairly static.

A recent presentation by @danielbohannon and @matthewdunwoody 

https://www.slideshare.net/DanielBohannon2/signaturesaredead-long-live-resilient-signatures

Serve as a reminder that tests need to be more dynamic, less defenders get complacent with curent detections.

I propose some sort of dynamic configuration file that can be applied to a test.  To change things like  file name, command line arguments, etc...

Open to feedback.  Just wanted to track as an issue to come back to when we have time.

**Comment by bfuzzy** [comment]
Yes please.
