### ISSUE TITLE
Contribute Ansible Execution Framework

### ISSUE THREAD

**Issue by tuckner** [redcanaryco/atomic-red-team#400]
Unsure if a PR would be better, but I wanted to possibly contribute a new execution framework that is an Ansible plugin.

https://github.com/tuckner/ansible-art

The plugin would be a part of Ansible's software package but would execute atomic techniques across Windows & Linux.

**Comment by caseysmithrc** [comment]
I think for now, lets keep this in a separate repo, but once you have it of the ground, let us know and we can keep cross reference it in our Related Projects here https://atomicredteam.io/related
Keep us posted on the progress.
-Cheers
