### ISSUE TITLE
Simple How To Get Started

### ISSUE THREAD

**Issue by caseysmithrc** [redcanaryco/atomic-red-team#432]
# Report
Currently the execution frameworks are not intuitive to help guide someone new to Atomic to know where to begin to run tests.

So perhaps we need to add a quick pointer to each framework with a brief description.

**Comment by vdog90** [comment]
I second this!  I just so happened to find the invoke-AtomicTest execution framework.  As a new user, all I wanted to do is execute my first test, then find out how to execute multiple tests.  I had to manually search the repo files, review code and comments to discover this.  I think it is better for new users like me to use and better understand the invoke-AtomicTest execution framework.   I think adding clarity on the project's main page will help.

When I finally found invoke-AtomicTest, I got it to execute but i had the following questions on this page
https://github.com/redcanaryco/atomic-red-team/tree/master/execution-frameworks/Invoke-AtomicRedTeam :
1. What does “GenerateOnly” mean?
2. What does “Confirm” do?
3. What are ConfirmPreferences and the available options? What do they do?
4. How do execute multiple tests?  All OS applicable tests?
5. Are there output options available?

Perhaps the readme's can be clarified.

Thanks!
