### ISSUE TITLE
Execute Get-keystroke script

### ISSUE THREAD

**Issue by SofiaArancibia** [redcanaryco/atomic-red-team#434]
# Report

## What did you do?

Run `https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1056/Get-Keystrokes.ps1`

## What did you expect to happen?

Script ¿should? log keystrokes at key.log

## What happened instead?

nothing

## Your Environment

* Windows 10, 64 bits
* Did you run the test from an elevated or root prompt? Yes
* If relevant, which atomic test is this specific to? T1056
* If relevant, which [execution harness](2) are you attempting to use? -

[1]: https://github.com/redcanaryco/atomic-red-team/tree/master/atomics "atomic tests"
[2]: https://github.com/redcanaryco/atomic-red-team/tree/master/execution-frameworks "execution frameworks"

**Comment by caseysmithrc** [comment]
Be sure to provide a path or the default location will be in the temp folder , like this
C:\Users\Research\AppData\Local\Temp\key.log
