### ISSUE TITLE
YAML Schema Modify - Check dependency exists 

### ISSUE THREAD

**Issue by mpgough** [redcanaryco/atomic-red-team#453]
As discussed in the Channel it would be great to have a the ability to check a dependency is on the box you are running the test from. For example LOLbins such as mavinject (T1055). In my testing (Win10 Enterprise x64) this is not always installed by default unless you have installed a click to run MS installer.

**Comment by clr2of8** [comment]
The schema has been modified to include "prereq_commands", the powershell executer runs the prereq commands with -CheckPrereqs flag. Not all tests have their prerequ commands written yet though.
