### ISSUE TITLE
T1197.yaml - Test #3 has duplicated argument

### ISSUE THREAD

**Issue by phr3sh** [redcanaryco/atomic-red-team#463]
# Report

## What did you do?

ℹ Please replace this with what you did.
Given:
bits_job_name | Name of BITS job | string | AtomicBITS
command_path | Path of command to execute | path | C:\Windows\system32\notepad.exe
command_line | Command line to execute | string | notepad.exe C:\Windows\Temp\bitsadmin_flag.ps1

The third step if this test case:
`bitsadmin.exe /setnotifycmdline #{bits_job_name} #{command_path} #{command_line}`

Is interpreted as: 
`bitsadmin.exe /setnotifycmdline AtomicBITS C:\Windows\system32\notepad.exe notepad.exe C:\Windows\Temp\bitsadmin_flag.ps1`

Notice how notepad.exe is duplicated.

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.
e.g. The atomic test executes and `notepad.exe` is launched.

## What happened instead?

ℹ Please replace this with of what happened instead.
notepad.exe is not launched.

## Your Environment

* Which *specific* operating system are you running (e.g. Windows 7 SP1 32-bit)?
Windows10
* Did you run the test from an elevated or root prompt?
No
* If relevant, which atomic test is this specific to?
"T1197 - BITS Jobs : Atomic Test #3 - Persist, Download, & Execute"
* If relevant, which [execution harness](2) are you attempting to use?
python

[1]: https://github.com/redcanaryco/atomic-red-team/tree/master/atomics "atomic tests"
[2]: https://github.com/redcanaryco/atomic-red-team/tree/master/execution-frameworks "execution frameworks"

**Comment by MHaggis** [comment]
All set! Thank you
