### ISSUE TITLE
T1197.yaml - Test #3 file can't be read

### ISSUE THREAD

**Issue by phr3sh** [redcanaryco/atomic-red-team#464]
# Report

## What did you do?
Run
bitsadmin.exe /create AtomicBITS
bitsadmin.exe /addfile AtomicBITS https://raw.githubusercontent.com/redcanaryco/atomic-red-team/master/atomics/T1197/T1197.md C:\Windows\Temp\bitsadmin_flag.ps1
bitsadmin.exe /setnotifycmdline C:\Windows\system32\notepad.exe C:\Windows\Temp\bitsadmin_flag.ps1
bitsadmin.exe /resume AtomicBITS

## What did you expect to happen?
The atomic test executes and `notepad.exe` is launched showing the contents of C:\Windows\Temp\bitsadmin_flag.ps1

## What happened instead?
The atomic test executes and `notepad.exe` is launched but doesnt display the file.

I think this is because bitsadmin doesn't make the file available until the job is completed with:
`bitsadmin.exe /complete AtomicBITS`
And without the file available, there's nothing for notepad.exe to display.

## Your Environment

* Which *specific* operating system are you running (e.g. Windows 7 SP1 32-bit)?
Windows10
* Did you run the test from an elevated or root prompt?
No
* If relevant, which atomic test is this specific to?
T1197 - BITS Jobs : Atomic Test #3 - Persist, Download, & Execute
* If relevant, which [execution harness](2) are you attempting to use?
python

[1]: https://github.com/redcanaryco/atomic-red-team/tree/master/atomics "atomic tests"
[2]: https://github.com/redcanaryco/atomic-red-team/tree/master/execution-frameworks "execution frameworks"

**Comment by MHaggis** [comment]
All set! Thank you
