### ISSUE TITLE
T1220.yaml - wmic command to open/execute xsl file is missing quotes

### ISSUE THREAD

**Issue by phr3sh** [redcanaryco/atomic-red-team#467]
# Report

## What did you do?
Run `wmic.exe #{wmic_command} /FORMAT:#{local_xsl_file}`

## What did you expect to happen?
The atomic test executes and `calc.exe` is launched.

## What happened instead?
We get an error from wmic.exe for invalid argument.

I think the fix is to add quotes around the path to the xsl file.
`wmic.exe #{wmic_command} /FORMAT:"#{local_xsl_file}"`

## Your Environment
* Which *specific* operating system are you running (e.g. Windows 7 SP1 32-bit)?
Windows10
* Did you run the test from an elevated or root prompt?
No
* If relevant, which atomic test is this specific to?
T1220 - #3 - WMIC bypass using local XSL file
T1220 - #4 - WMIC bypass using remote XSL file
* If relevant, which [execution harness](2) are you attempting to use?
Python

[1]: https://github.com/redcanaryco/atomic-red-team/tree/master/atomics "atomic tests"
[2]: https://github.com/redcanaryco/atomic-red-team/tree/master/execution-frameworks "execution frameworks"

**Comment by MHaggis** [comment]
Hi @phr3sh , 
When running this test did you modify the local paths of both files? Default is:
`C:\AtomicRedTeam\atomics\T1220\src\`

**Comment by caseysmithrc** [comment]
We will fix. The root issue is the '-" in the file name.  So we just renamed the files moving forward. 

Thanks!

**Comment by MHaggis** [comment]
All set! Thank you!
