### ISSUE TITLE
Extend Schema to Include Tactic

### ISSUE THREAD

**Issue by caseysmithrc** [redcanaryco/atomic-red-team#469]
By extending the schema to include MITRE ATT&CK Tactic, you could enable tests of all Tactics we currently have tests for etc...

Would be easy enough to add to extend.  Or we could poll API Dynamically...etc...

**Comment by keithmccammon** [comment]
@caseysmithrc I believe that we want to use a singular identifier for each atomic test, and the lowest-level identifier possible. If we include the Tactic in the schema, then we're faced with keeping that data in sync if a Technique is moved between Tactics, or is included in more than one Tactic.

To achieve what you're after, we may try extending an execution framework to look up all Techniques, and then group by Tactic prior to execution. Would that do the trick?

**Comment by caseysmithrc** [comment]
Yup that works.
