### ISSUE TITLE
ATT&CK Layer Fails to load in Enterprise-Navigator

### ISSUE THREAD

**Issue by Scoubi** [redcanaryco/atomic-red-team#477]
# Report

## What did you do?

Download `https://github.com/redcanaryco/atomic-red-team/blob/master/atomic_red_team/enterprise-attack.json`
Load it in `https://mitre-attack.github.io/attack-navigator/enterprise/`

## What did you expect to happen?

Load the Layer and color the TTP that ART covers

## What happened instead?

Error message `WARNING: Uploaded layer version (undefined) does not match Navigator's layer version (2.1). The layer configuration may not be fully restored.`

## Your Environment

OSX Mojave
Firefox 65.0.1

**Comment by ForensicITGuy** [comment]
This is now fixed.
