### ISSUE TITLE
No Pre-Attack Test Cases found

### ISSUE THREAD

**Issue by cstayyab** [redcanaryco/atomic-red-team#496]
I tried to execute secveral Pre-Attack Techniques. Are they in the scope of current repository or are you planning to provide tests for that also?

**Comment by keithmccammon** [comment]
@cstayyab At present, this project remains focused on Enterprise ATT&CK. It's unclear how Pre-ATT&CK would be "tested", as these techniques are things that adversaries do unilaterally, in almost all cases (i.e., putting up their C2 infrastructure, acquisition, targeting, etc.). 

In light of the above, I'll close this out. But do feel free to re-open if you feel that we're missing something. Thank you!
