### ISSUE TITLE
T1007  - invalid service name

### ISSUE THREAD

**Issue by hkelley** [redcanaryco/atomic-red-team#499]
# Report
Invalid service name used as default for T1007

## What did you do?

Invoke-AtomicTest -AtomicTechnique $at

## What did you expect to happen?

net.exe commands should be tested

## What happened instead?

[SC] StartService: OpenService FAILED 1060:
The specified service does not exist as an installed service.

[SC] OpenService FAILED 1060:
The specified service does not exist as an installed service.

## Your Environment
Windows 10 x64

**Comment by MHaggis** [comment]
Hi @hkelley,
I manually ran the test and it works (running as Admin). Can you provide any additional details on the test you performed? Feel free to copy/paste the entire command and output.

**Comment by hkelley** [comment]
Running as admin.

Command is 

`& 'C:\_Active\MITRE_ATT&CK\utils\run-atomic-demo.ps1' -atinstalldir  "C:\XXXXX\AtomicRedTeam\atomic-red-team-master" -attackID T1007
`

**Script is attached.**  
[run-atomic-demo.ps1.txt](https://github.com/redcanaryco/atomic-red-team/files/3163659/run-atomic-demo.ps1.txt)

**Output is:**
```
[SC] StartService: OpenService FAILED 1060:

The specified service does not exist as an installed service.

```
