### ISSUE TITLE
Errors during installation

### ISSUE THREAD

**Issue by p57p57** [redcanaryco/atomic-red-team#516]
# Report

## What did you do?

powershell.exe "IEX (New-Object Net.WebClient).DownloadString('http://psInstall.AtomicRedTeam.com')" *>>C:\loginstall.txt

## What did you expect to happen?

installation without errors

Note that the installation path is 
C:\AtomicRedTeam\atomic-red-team-master

## What happened instead?

Directory: C:\

Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----       16/07/2019     13:06                AtomicRedTeam                                                         

FastPackageReference : https://onegetcdn.azureedge.net/providers/nuget-2.8.5.208.package.swidtag
ProviderName         : Bootstrap
Source               : https://onegetcdn.azureedge.net/providers/nuget-2.8.5.208.package.swidtag
Status               : Installed
SearchKey            : https://onegetcdn.azureedge.net/providers/nuget-2.8.5.208.package.swidtag
FullPath             : 
PackageFilename      : Microsoft.PackageManagement.NuGetProvider.dll
FromTrustedSource    : False
Summary              : NuGet provider for the OneGet meta-package manager
SwidTags             : {nuget}
CanonicalId          : bootstrap:nuget/2.8.5.208#https://onegetcdn.azureedge.net/providers/nuget-2.8.5.208.package.swid
                       tag
Metadata             : {summary,providerName,providerVersion,summary}
SwidTagText          : <?xml version="1.0" encoding="utf-16" standalone="yes"?>
                       <SoftwareIdentity
                         name="nuget"
                         version="2.8.5.208"
                         versionScheme="multipartnumeric" 
                       xmlns="http://standards.iso.org/iso/19770/-2/2015/schema.xsd">
                         <Meta
                           summary="NuGet provider for the OneGet meta-package manager" />
                         <Meta
                           providerName="nuget"
                           providerVersion="2.8.5.208"
                           summary="NuGet provider for the OneGet meta-package manager" />
                         <Link
                           href="https://onegetcdn.azureedge.net/providers/Microsoft.PackageManagement.NuGetProvider-2.
                       8.5.208.dll"
                           rel="installationmedia"
                           type="application/octet-stream"
                           media="(OS:windows)" />
                       </SoftwareIdentity>
Dependencies         : {}
IsCorpus             : 
Name                 : nuget
Version              : 2.8.5.208
VersionScheme        : multipartnumeric
TagVersion           : 
TagId                : 
IsPatch              : 
IsSupplemental       : 
AppliesToMedia       : 
Meta                 : {{summary}, {providerName,providerVersion,summary}}
Links                : {installationmedia:https://onegetcdn.azureedge.net/providers/Microsoft.PackageManagement.NuGetPr
                       ovider-2.8.5.208.dll}
Entities             : {}
Payload              : 
Evidence             : 
Culture              : 
Attributes           : {name,version,versionScheme}

powershell.exe : Import-Module : The specified module 
At line:1 char:1
+ powershell.exe "IEX (New-Object Net.WebClient).DownloadString('http:/ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Import-Module : The specified module :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
'C:\AtomicRedTeam\execution-frameworks\Invoke-AtomicRedTeam\Invoke-AtomicRedTeam\Invoke-AtomicRedTeam.psm1' was not 

loaded because no valid module file was found in any module directory.

At line:111 char:2

+     Import-Module "$InstallPath\execution-frameworks\Invoke-AtomicRed ...

+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : ResourceUnavailable: (C:\AtomicRedTea...micRedTeam.psm1:String) [Import-Module], FileNot 

   FoundException

    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

 

cd : Cannot find path 'C:\AtomicRedTeam\execution-frameworks\Invoke-AtomicRedTeam\Invoke-AtomicRedTeam\' because it 

does not exist.

At line:114 char:2

+     cd "$InstallPath\execution-frameworks\Invoke-AtomicRedTeam\Invoke ...

+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : ObjectNotFound: (C:\AtomicRedTea...-AtomicRedTeam\:String) [Set-Location], ItemNotFoundE 

   xception

    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

 

Installation of Invoke-AtomicRedTeam is complete

## Your Environment

Windows10

**Comment by caseysmithrc** [comment]
Thank you, I'll take a look today to fix this.

**Comment by p57p57** [comment]
> 
> 
> Thank you, I'll take a look today to fix this.

Hi Casey, seems that you haven't had time to fix this issue. Do you plan to do it ?

Best Regards

**Comment by MHaggis** [comment]
We're looking into this now and will get a fix out today.

**Comment by MHaggis** [comment]
This is all set! Let me know if you run into any further issues @p57p57
