### ISSUE TITLE
PowerShell Fileless Script Execution Test Error

### ISSUE THREAD

**Issue by destsubscription** [redcanaryco/atomic-red-team#606]
# Report
The PowerShell Fileless Script Execution doesn't work, due to iex interpreting the -path variable as a switch in Invoke-Expression, not within Set-Content.
See output below.

PS C:\Users\test> powershell.exe -noprofile -windowstyle hidden -executionpolicy bypass iex ([Text.Encoding]::ASCII.GetString([Convert]::FromBase64String((gp 'HKCU:\Software\Classes\AtomicRedTeam').ART)))
powershell.exe : Invoke-Expression : A parameter cannot be found that matches parameter name 'path'.
At line:1 char:1
+ powershell.exe -noprofile -windowstyle hidden -executionpolicy bypass ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Invoke-Expressi...er name 'path'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
At line:1 char:17
+ iex Set-Content -path $env:SystemRoot/Temp/art-marker.txt -value Hell ...
+                 ~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-Expression], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.InvokeExpressionCommand

## What did you do?
Please amend to the following:

- name: PowerShell Fileless Script Execution
  description: |
   Execution of a PowerShell payload from the Windows Registry similar to that seen in fileless malware infections.

  supported_platforms:
    - windows

  executor:
    name: command_prompt
    elevation_required: false
    command: |
      reg.exe add "HKEY_CURRENT_USER\Software\Classes\AtomicRedTeam" /v ART /t REG_SZ /d "U2V0LUNvbnRlbnQgLXBhdGggIiRlbnY6U3lzdGVtUm9vdC9UZW1wL2FydC1tYXJrZXIudHh0IiAtdmFsdWUgIkhlbGxvIGZyb20gdGhlIEF0b21pYyBSZWQgVGVhbSI="
      powershell.exe -noprofile -windowstyle hidden -executionpolicy bypass "& {([Text.Encoding]::ASCII.GetString([Convert]::FromBase64String((gp 'HKCU:\Software\Classes\AtomicRedTeam').ART))) | iex }"
    cleanup_command: |
      del %SystemRoot%\Temp\art-marker.txt;
      REG DELETE "HKEY_CURRENT_USER\Software\Classes\AtomicRedTeam" /f

**Comment by clr2of8** [comment]
Could you provide the atomic Technique number (T#) and attack name?

**Comment by destsubscription** [comment]
T1086
- name: PowerShell Fileless Script Execution
  description: |
   Execution of a PowerShell payload from the Windows Registry similar to that seen in fileless malware infections.

**Comment by clr2of8** [comment]
this appears to have been fixed in pull #635, error no long seen. thank you for reporting this issue
