### ISSUE TITLE
Todo - PowerShell Profile

### ISSUE THREAD

**Issue by ForensicITGuy** [redcanaryco/atomic-red-team#636]
Want to implement a PowerShell profile test.

# References
https://pentestlab.blog/2019/11/05/persistence-powershell-profile/
https://attack.mitre.org/techniques/T1504/
https://www.welivesecurity.com/2019/05/29/turla-powershell-usage/

**Comment by clr2of8** [comment]
Test added in pull #668 by morgansec.
