### ISSUE TITLE
Component Object Model Hijacking not success

### ISSUE THREAD

**Issue by Greekers** [redcanaryco/atomic-red-team#714]
ℹ 
reg import PathToAtomicsFolder\T1122\src\COMHijack.reg
certutil.exe -CAInfo

ℹ  The atomic test executes and `calc.exe` is launched.
I tested it in intranet  enviroment and replace the reg url into intranet url

ℹ Please replace this with of what happened instead.
nothing happened

## MY Environment

* Windows 7 SP1 64-bit
* Did you run the test from an elevated or root prompt? yes
* If relevant, which atomic test is this specific to?
* If relevant, which [execution harness](2) are you attempting to use?

https://github.com/Greekers/atomic-red-team/blob/master/atomics/T1122/T1122.md

**Comment by clr2of8** [comment]
Removed this test via pull #798 until test can be made functional
