### ISSUE TITLE
T1085: Add timeout to command executed so the remaining test case can carry on

### ISSUE THREAD

**Issue by sunnyneo** [redcanaryco/atomic-red-team#766]
# Report

## What did you do?

ℹ Please replace this with what you  did.
Ran Invoke-AtomicTest T1085
## What did you expect to happen?

The atomic test executes the first case and `notepad.exe` is launched. And the rest of the test cases should continue to run after the first test case is executed

## What happened instead?

The execution was stuck at the first test case and no progress to another test cases. T1085 has a total of 6 test cases.

## Your Environment

* Which *specific* operating system are you running (e.g. Windows 7 SP1 32-bit)?
* Did you run the test from an elevated or root prompt?
* If relevant, which atomic test is this specific to?
* If relevant, which [execution harness](2) are you attempting to use?

Host Name:                 WIN10 
OS Name:                   Microsoft Windows 10 Enterprise Evaluation 
OS Version:                10.0.18362 N/A Build 18362
Architecture:              x64

Ran the command from elevated powershell 

[1]: https://github.com/redcanaryco/atomic-red-team/tree/master/atomics "atomic tests"
[2]: https://github.com/redcanaryco/atomic-red-team/tree/master/execution-frameworks "execution frameworks"

**Comment by clr2of8** [comment]
Thank you for reporting. This is definitely an issue. I'm working on a fix now.

**Comment by clr2of8** [comment]
pull #790 added a 2 minute timeout to all command blocks. You can set you own timeout with the `-TimeoutSeconds` parameter
