### ISSUE TITLE
Improvement: Create releases of the Atomic Red Team Framework

### ISSUE THREAD

**Issue by P4T12ICK** [redcanaryco/atomic-red-team#769]
I think it would be very good for a lot of users of this framework to have releases. For example, we (Security Research Team of Splunk) are using the Atomic Red Team Framework in our Attack Range (https://github.com/splunk/attack_range). If something is broken on the master branch, it will be automatically also be broken in other projects using the Atomic Red Team framework.
If there would be releases, we (and other users) could always pull the latest stable release.

**Comment by MHaggis** [comment]
Thank you @P4T12ICK for the feedback. We're going to look into this going forward.

**Comment by clr2of8** [comment]
Pull #790 doesn't completely address this but it allows you to specify which repo owner and branch to install from so that you can manage your own releases and branches from a fork of this repo for added stability. I hope this is enough to fill you immediate needs. Thank you.
