### ISSUE TITLE
Didn't find any VBScript in T1193\bin\PowerShell_IP_Doc.doc

### ISSUE THREAD

**Issue by snappyJack** [redcanaryco/atomic-red-team#779]
i follow this `https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1193/T1193.md#atomic-test-2---word-spawned-a-command-shell-and-used-an-ip-address-in-the-command-line`

when I run this in powershell,and didn't exec any VBScript 
```
Start-Process $PathToAtomicsFolder\T1193\bin\PowerShell_IP_Doc.doc
```
then I start to find VBScript in doc,and nothing found
![image](https://user-images.githubusercontent.com/16055573/72403135-10801500-378c-11ea-9c3a-114634ecc2d4.png)

**Comment by clr2of8** [comment]
Removed this test via pull #805 until it can be fixed.
