### ISSUE TITLE
T1014- PuppetString.exe error: 00000241

### ISSUE THREAD

**Issue by Andras32** [redcanaryco/atomic-red-team#809]
# Report

## What did you do?
While updating T1014 to work with the new dependency functionality I ran across and error.

ℹ Created branch https://github.com/Andras32/atomic-red-team/tree/T1014-3Update
Ran: 
Invoke-AtomicTest T1014 -CheckPrereqs  
Invoke-AtomicTest T1014 -GetPrereqs
Invoke-AtomicTest T1014

## What did you expect to happen?

ℹ I expected the test to complete as referenced in https://zerosum0x0.blogspot.com/2017/07/puppet-strings-dirty-secret-for-free.html

## What happened instead?

ℹ PuppetString.exe error: 00000241

## Your Environment

* Which *specific* operating system are you running (e.g. Windows 7 SP1 32-bit)?
Win10 x64
* Did you run the test from an elevated or root prompt?
Yes if you don't you get error 00000005
* If relevant, which atomic test is this specific to?
T1014 -TestNumber 3
* If relevant, which [execution harness](2) are you attempting to use?
Invoke-AtomicTest

**Comment by Andras32** [comment]
The test referenced in https://github.com/Andras32/atomic-red-team/tree/T1014-3Update
utilizes https://github.com/FuzzySecurity/Capcom-Rootkit/blob/c887fb87b1a1294fc43920d6694868cd7a24eacb/Driver/Capcom.sys

I found this repo while reading the reference material. Is this the correct driver to run this test against?

**Comment by M0rbidAngel** [comment]
That is the correct driver.  A while back a decision was made not to include | distribute that driver with the repo.  So you can install that and the rootkit test should work fine.

**Comment by Andras32** [comment]
Thanks @M0rbidAngel I'll give it a go.

**Comment by M0rbidAngel** [comment]
I tested it this evening it works fine. The reason I like that tool is it loads the driver and runs the test all in a single binary. 


<img width="1063" alt="Screen Shot 2020-02-05 at 7 56 39 PM" src="https://user-images.githubusercontent.com/54870076/73902034-cbfb0d00-4851-11ea-81d3-f897dadca22f.png">
