### ISSUE TITLE
T1118 - missing dll

### ISSUE THREAD

**Issue by randomguy74** [redcanaryco/atomic-red-team#833]
it seems that the dll is missing in /t1118/src/ folder

**Comment by MHaggis** [comment]
Hi @randomguy74 !
That is correct. We provided the src .cs file in there but not the compiled .dll. The first task in the atomic test is to compile the dll from source:

`C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe /target:library /out:#{filename} #{source}`

After that, it will execute:

`C:\Windows\Microsoft.NET\Framework\v4.0.30319\InstallUtil.exe /? #{filename}`

Does that help?

**Comment by clr2of8** [comment]
Correct, those DLL files get compiled from source as part of the test. Pull request #872 by @mgraeber-rc, which was merged just now, also cleans up and clarifies these tests. Thanks!
