### ISSUE TITLE
T1193 should  execute the attachement as well

### ISSUE THREAD

**Issue by Xumeiquer** [redcanaryco/atomic-red-team#841]
# Report

When a spearphishing gets into the user's inbox the users apart from downloading the attachment they usually open the file, otherwise, the attack is incomplete. 

https://attack.mitre.org/techniques/T1193/

## What did you expect to happen?

When executing this technique I expect the downloaded file gets executed.

## What happened instead?

The attachment file got downloaded from GitHub but not executed.

## Your Environment

* Windows 10
* User without privileges
* Technique T1193

Kind Regards,

**Comment by Andras32** [comment]
@Xumeiquer Try the new tests under User Execution T1204. Those tests will help with creating host based detections for maldoc execution.

**Comment by cherokeejb** [comment]
After reviewing that idea, I after reading T1193 it is intended to micro-focus for the delivery phase only, via phishing, while others such as T1204 (User Execution) or T1203 (Explotation) would be where the actual doc would open.  I will probablly make a very similar test in 1204 while doing some cleanup soon.  As Andras said there are some new, similar ones there already. @clr2of8 do you agree to close the issue?

**Comment by Xumeiquer** [comment]
Thanks for your reply, I will have a look at those techniques.

**Comment by clr2of8** [comment]
Agreed, thanks everyone.
