### ISSUE TITLE
T1117 - executors #2 [Error : AllTheThingsx86.dll not found]

### ISSUE THREAD

**Issue by ravelim** [redcanaryco/atomic-red-team#864]
Hi,

I have attempted to launch T1117 : executors #2 and encountered the following error message.

Output: Microsoft Windows [Version 10.0.17763.379]
(c) 2018 Microsoft Corporation. All rights reserved."IF "%PROCESSOR_ARCHITECTURE%"=="AMD64" (C:\Windows\syswow64\regsvr32.exe /s C:\Users\IEUser\atomic-red-team\atomics\T1117\..\T1117\bin\AllTheThingsx86.dll) ELSE ( regsvr32.exe /s C:\Users\IEUser\atomic-red-team\atomics\T1117\..\T1117\bin\AllTheThingsx86.dll )"
The system cannot find the path specified.

Did a manual compile of .cs file and not successful

`C:\Users\IEUser>C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe /target:library /out:#{filename} C:\Users\IEUser\atomic-red-team\atomics\T1117\src\AllTheThings.cs
Microsoft (R) Visual C# Compiler version 4.8.3761.0
for C# 5
Copyright (C) Microsoft Corporation. All rights reserved.

This compiler is provided as part of the Microsoft (R) .NET Framework, but only supports language versions up to C# 5, which is no longer the latest version. For compilers that support newer versions of the C# programming language, see http://go.microsoft.com/fwlink/?LinkID=533240

atomic-red-team\atomics\T1117\src\AllTheThings.cs(7,7): error CS0246: The type or namespace name
        'RGiesecke' could not be found (are you missing a using directive or an assembly
        reference?)
atomic-red-team\atomics\T1117\src\AllTheThings.cs(145,6): error CS0246: The type or namespace
        name 'DllExport' could not be found (are you missing a using directive or an assembly
        reference?)
atomic-red-team\atomics\T1117\src\AllTheThings.cs(145,6): error CS0246: The type or namespace
        name 'DllExportAttribute' could not be found (are you missing a using directive or an
        assembly reference?)
atomic-red-team\atomics\T1117\src\AllTheThings.cs(151,6): error CS0246: The type or namespace
        name 'DllExport' could not be found (are you missing a using directive or an assembly
        reference?)
atomic-red-team\atomics\T1117\src\AllTheThings.cs(151,6): error CS0246: The type or namespace
        name 'DllExportAttribute' could not be found (are you missing a using directive or an
        assembly reference?)
atomic-red-team\atomics\T1117\src\AllTheThings.cs(158,6): error CS0246: The type or namespace
        name 'DllExport' could not be found (are you missing a using directive or an assembly
        reference?)
atomic-red-team\atomics\T1117\src\AllTheThings.cs(158,6): error CS0246: The type or namespace
        name 'DllExportAttribute' could not be found (are you missing a using directive or an
        assembly reference?)
atomic-red-team\atomics\T1117\src\AllTheThings.cs(165,6): error CS0246: The type or namespace
        name 'DllExport' could not be found (are you missing a using directive or an assembly
        reference?)
atomic-red-team\atomics\T1117\src\AllTheThings.cs(165,6): error CS0246: The type or namespace
        name 'DllExportAttribute' could not be found (are you missing a using directive or an
        assembly reference?)`

**Comment by ravelim** [comment]
Hi,

I attempt to launch T1117 : executors #2 and encountered the following error message.

Output: Microsoft Windows [Version 10.0.17763.379]
(c) 2018 Microsoft Corporation. All rights reserved."IF "%PROCESSOR_ARCHITECTURE%"=="AMD64" (C:\Windows\syswow64\regsvr32.exe /s C:\Users\IEUser\atomic-red-team\atomics\T1117\..\T1117\bin\AllTheThingsx86.dll) ELSE ( regsvr32.exe /s C:\Users\IEUser\atomic-red-team\atomics\T1117\..\T1117\bin\AllTheThingsx86.dll )"
The system cannot find the path specified.


I attempted to manually compile the file and seem like there missing reference. 

`C:\Users\IEUser>C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe /target:library /out:#{filename} C:\Users\IEUser\atomic-red-team\atomics\T1117\src\AllTheThings.cs
Microsoft (R) Visual C# Compiler version 4.8.3761.0
for C# 5
Copyright (C) Microsoft Corporation. All rights reserved.

This compiler is provided as part of the Microsoft (R) .NET Framework, but only supports language versions up to C# 5, which is no longer the latest version. For compilers that support newer versions of the C# programming language, see http://go.microsoft.com/fwlink/?LinkID=533240

atomic-red-team\atomics\T1117\src\AllTheThings.cs(7,7): error CS0246: The type or namespace name
        'RGiesecke' could not be found (are you missing a using directive or an assembly
        reference?)
atomic-red-team\atomics\T1117\src\AllTheThings.cs(145,6): error CS0246: The type or namespace
        name 'DllExport' could not be found (are you missing a using directive or an assembly
        reference?)
atomic-red-team\atomics\T1117\src\AllTheThings.cs(145,6): error CS0246: The type or namespace
        name 'DllExportAttribute' could not be found (are you missing a using directive or an
        assembly reference?)
atomic-red-team\atomics\T1117\src\AllTheThings.cs(151,6): error CS0246: The type or namespace
        name 'DllExport' could not be found (are you missing a using directive or an assembly
        reference?)
atomic-red-team\atomics\T1117\src\AllTheThings.cs(151,6): error CS0246: The type or namespace
        name 'DllExportAttribute' could not be found (are you missing a using directive or an
        assembly reference?)
atomic-red-team\atomics\T1117\src\AllTheThings.cs(158,6): error CS0246: The type or namespace
        name 'DllExport' could not be found (are you missing a using directive or an assembly
        reference?)
atomic-red-team\atomics\T1117\src\AllTheThings.cs(158,6): error CS0246: The type or namespace
        name 'DllExportAttribute' could not be found (are you missing a using directive or an
        assembly reference?)
atomic-red-team\atomics\T1117\src\AllTheThings.cs(165,6): error CS0246: The type or namespace
        name 'DllExport' could not be found (are you missing a using directive or an assembly
        reference?)
atomic-red-team\atomics\T1117\src\AllTheThings.cs(165,6): error CS0246: The type or namespace
        name 'DllExportAttribute' could not be found (are you missing a using directive or an
        assembly reference?)`

**Comment by clr2of8** [comment]
DLL's added in PR #885
