### ISSUE TITLE
ART should create directories when prompting for an output directory

### ISSUE THREAD

**Issue by tbennett6421** [redcanaryco/atomic-red-team#893]
# Report
ART runner should create non-existent directories if provided by the user

## What did you do?
```
Enter the name of the technique that you would like to execute (eg. T1033).  Type 'exit' to quit.
> T1087

Please choose your executors: (space-separated list of numbers): 1

-----------------------------------------------------------
Name: View sudoers access
Description: (requires root)
Platforms: linux, macos

Arguments:
output_file: Path where captured results will be placed (default: ~/loot.txt)

Launcher: sh
Command: cat /etc/sudoers > #{output_file}

Do you want to run this?  (Y/n): y
Please provide a parameter for 'output_file' (blank for default): /Users/myaccount/Desktop/artifacts/T1087/test1.output
In order to run this non-interactively:
    Python:
    techniques = runner.AtomicRunner()
    techniques.execute("T1087", position=1, parameters={'output_file': '/Users/myaccount/Desktop/artifacts/T1087/test1.output'})
    Shell Script:
    python3 runner.py run T1087 1 --args '{"output_file": "/Users/myaccount/Desktop/artifacts/T1087/test1.output"}' 

------------------------------------------------
Output: /bin/sh: line 1: /Users/myaccount/Desktop/artifacts/T1087/test1.output: No such file or directory
```

## What did you expect to happen?
ART would create the required output directories, execute the test and log output to the requested output file.

## What happened instead?

ℹ Please replace this with of what happened instead.
Output: /bin/sh: line 1: /Users/myaccount/Desktop/artifacts/T1087/test1.output: No such file or directory
Additionally the test didn't execute.

## Your Environment
* Which *specific* operating system are you running (e.g. Windows 7 SP1 32-bit)?
Mac OS X 10.14.6
* Did you run the test from an elevated or root prompt?
ran from a standard prompt

[1]: https://github.com/redcanaryco/atomic-red-team/tree/master/atomics "atomic tests"
[2]: https://github.com/redcanaryco/atomic-red-team/tree/master/execution-frameworks "execution frameworks"

**Comment by tbennett6421** [comment]
If I get time I can submit a PR to do this, should be as simple as using a try catch block to handle

**Comment by clr2of8** [comment]
Python Execution Framework no longer maintained in this repo.
