### ISSUE TITLE
Cross-platform changes must be duplicated

### ISSUE THREAD

**Issue by ahogue-atlassian** [redcanaryco/atomic-red-team#92]
With the current directory structure, any techniques that work on Windows, Mac, and Linux must be duplicated. This is cumbersome for when one of them changes, as then the other two must also be changed in the same way.

This could be addressed by making a `Common` directory which contains cross-platform resources. The READMEs in each of the OS-specific directories could then link back to resources in the `Common` directory.

**Comment by caseysmithrc** [comment]
This is good feedback, we are working on some restructuring and I think we will incorporate some YAML that will let us tag things rather than putting them in tags similar to the way that Chris Gates has done in Metta.
https://github.com/uber-common/metta
I'll leave this open for now, until we have better guidance

**Comment by brianebeyer** [comment]
Hi @ahogue-atlassian - can you take a look at the new YAML spec for atomics and the contribution guide here? https://github.com/redcanaryco/atomic-red-team/blob/master/CONTRIBUTIONS.md

I think this is a good solution for keeping tests similar and keeping any supporting materials next to the test's definition. It also gives us the ability to use YAML merges to share config across tests in the same technique.

There are still cases where we'll want to share supporting materials across techniques, which I think we'll want to use git committed symlinks for.

Does the new structure resolve your original concern, or did we miss the mark?

**Comment by brianebeyer** [comment]
I believe this is fixed in YAML restructuring. @ahogue-atlassian, please reopen if that's not the case. We'd love your feedback on this-
