### ISSUE TITLE
t1086 Hangs on run

### ISSUE THREAD

**Issue by s-koniarz** [redcanaryco/atomic-red-team#953]
# Report

## What did you do?

Attempted to run test T1086 using https://github.com/splunk/attack_range to facilitate the red team test.  

## What did you expect to happen?

Expected the test to run successfully and return with a good run.  

## What happened instead?

**The test hangs at this atomic test.**
```
- name: Mimikatz - Cradlecraft PsSendKeys
  description: |
    Run mimikatz via PsSendKeys
```

**Error when running command in test manually:**
```
IEX : At line:1 char:8
+ [Window Title]
+        ~
Missing ] at end of attribute or type literal.
At line:1 char:9
+ [Window Title]
+         ~~~~~~
Unexpected token 'Title]' in expression or statement.
At line:1 char:1428
+ ... Item Variable:_).Value $props.((Variable _).Value)};IEX($res);invoke- ...
+                                                         ~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : EndSquareBracketExpectedAtEndOfAttribute,Microsoft.PowerShell.Commands.InvokeExpressionCommand
```
 
**Testing Done**
I also tested the T1086 with removing the one specific atomic test and it completed successfully.  

## Your Environment

* Which *specific* operating system are you running (e.g. Windows 7 SP1 32-bit)? Windows Server 2016
* Did you run the test from an elevated or root prompt? Elevated Privs 
* If relevant, which atomic test is this specific to? T1086
* If relevant, which [execution harness](2) are you attempting to use? 

[1]: https://github.com/redcanaryco/atomic-red-team/tree/master/atomics "atomic tests"
[2]: https://github.com/redcanaryco/atomic-red-team/tree/master/execution-frameworks "execution frameworks"

**Comment by clr2of8** [comment]
Thank you for submitting, when I ran the test on Win10 it worked as expected. Is it still causing problems for you?

**Comment by clr2of8** [comment]
closing until confirmed to still be an issue
