### ISSUE TITLE
T1077 test doesn't belong

### ISSUE THREAD

**Issue by keithmccammon** [redcanaryco/atomic-red-team#998]
# Report
[Test #3 for T1077](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1077/T1077.md#atomic-test-3---copy-and-execute-file-with-psexec) isn't representative of the Windows Admin Shares technique.

If changed to use an admin share, it should stay.

Else, it should be moved to T1035.

## What did you do?

N/A

## What did you expect to happen?

N/A

## What happened instead?

N/A

## Your Environment

N/A

**Comment by clr2of8** [comment]
Keith, is this still a problem after we moved to sub-techniques?

**Comment by keithmccammon** [comment]
I'm going to close this out as OBE (the link to the technique is broken now) :)
